#+BEGIN_HTML
---
layout: post
title: 和寶寶共睡大床的注意事項
categories: [education]
tags: [baby]
---
#+END_HTML

#+BEGIN_HTML
<iframe src="https://www.flickr.com/photos/kimim-photo/11619794296/player/f05a1a6747" height="480" width="640"  frameborder="0" allowfullscreen webkitallowfullscreen mozallowfullscreen oallowfullscreen msallowfullscreen></iframe>
#+END_HTML

最近發現讓寶寶和大人一起睡大床可以很好的促進寶寶睡眠，減少寶寶夜裡醒來的次數。但是和寶寶一起睡大床會有一些潛在的風險，因此要時刻留意一些安全注意事項。

* 絕對不可以把寶寶一個人丟在大床上
哪怕是很小的嬰兒也會在床上翻滾。所以就有可能從床沿滾下床。因此，絕對不可以把寶寶一個人留在比較高的地方，比如大床上，桌子上。

* 把寶寶放在穩固整潔的床面，給他蓋上相對較輕的毯子
太柔軟的床面、被單和大人的衣服等很容易造成寶寶窒息。因此一定要把寶寶放在穩固整潔的床面，不要蓋太多太厚柔軟的被子。最好把寶寶穩穩的放置在睡袋或者繈褓里，這樣就可以避免寶寶鼻子被被子覆蓋的風險。

* 絕對不要蓋住寶寶的頭
首先，絕對不要用被子蓋住寶寶的頭。另外，如果寶寶很愛動，還要確保寶寶不會爬出繈褓，從而被毯子蓋住頭部導致呼吸困難。因此在臨睡前，大人一定要確保寶寶不會有任何潛在的被棉被毯子蓋住頭部的風險。

* 不要把寶寶放在水床上
如果你用的是水床，那么，請把寶寶放在床邊的搖籃里。因為水床表面很軟，不穩固，很容易使寶寶陷入危險的睡姿。

* 絕對不要把寶寶放在枕頭上
因為枕頭是隆起的表面，寶寶很容易從枕頭上翻滾下來，不小心就會蓋住寶寶的臉，導致寶寶呼吸困難。

* 避免使用羊絨或絲絨等厚重的被單
羊毛絲絨材料被單很容易增加寶寶窒息的風險。請選擇材質較輕的棉毯。

* 不要在寶寶周圍防止毛絨玩具和枕頭
和寶寶一起睡覺前，一定要拿走那些柔軟的毛絨物體。這些枕頭，厚毯，毛絨玩具很容易覆蓋住寶寶的嘴巴和鼻子，使得寶寶面臨窒息的潛在風險。

* 確保床褥平整
折疊不平的床褥容易導致寶寶陷進床褥的褶皺里，導致呼吸困難。還容易讓寶寶睡眠不安穩，翻滾到床沿。

* 不要把寶寶放在睡椅上
寶寶躺在睡椅里很容易翻滾，臉部陷進彎曲的床面從而增加窒息風險。

* 檢查床沿和墻之間的空隙
如果床是擺在墻邊，一定要仔細檢查床沿和墻之間是否有空隙，不然寶寶容易陷進空隙里。另外還要檢查床頭和被單是否貼合，沒有空隙。

* 不要讓寶寶趴著睡覺
研究表明，寶寶仰著睡覺可以有效的降低 SIDS[fn:1]。因為當寶寶趴著睡覺的時候，嘴巴鼻子周圍空間很小，隨著寶寶的呼吸，二氧化碳的含量會變的比較高，長期這樣呼吸，寶寶吸入氧氣量不足，對寶寶健康很不利。所以當你側著餵好奶之後，要立即讓寶寶仰過來睡。

* 不要把小於 1 歲的寶寶和其他寶寶放在一張床上
把小寶寶和其他寶寶放在一起睡是很危險的。因為其他寶寶睡著了會翻滾，很容易把小寶寶的臉蓋住，從而導致呼吸困難。所以即使是媽媽在邊上也盡量避免讓寶寶擠在一起睡覺。

* 如果你服用安眠藥，吃藥，醉酒了，請避免和寶寶一起睡
因為家長吃藥，喝酒后睡覺意識模糊，容易翻滾壓到寶寶或者把寶寶踢下床，這樣是非常危險的！

* 請把過長的頭髮扎起來
在和寶寶一起睡覺前，請把長頭髮扎起來，這樣可以避免長頭髮擋住寶寶的臉或者勾住寶寶的頭和脖子。

* 母乳喂奶后，要及時調整睡姿
有的媽媽在給寶寶餵奶的時候睡著了，這樣媽媽的乳房很容易壓住寶寶的臉，導致寶寶呼吸困難，從而增加寶寶窒息的風險。2013年10月01日揚子晚報報道了一則新聞：母親凌晨餵奶犯困睡著，寶寶被捂窒息身亡[fn:2]。

* Footnotes

[fn:2] http://news.sina.com.cn/s/2013-10-01/045828344695.shtml

[fn:1] 婴儿猝死症，Sudden infant death syndrome (SIDS)^en ，Le syndrome de mort subite du nourrisson (MSN)^fr ，Der plötzliche Kindstod, plötzliche Säuglingstod oder Krippentod (lateinisch: Mors subita infantium)^de
