#+BEGIN_HTML
---
layout: post
title: 读书笔记：《断舍离 瑜伽篇》
categories: [education]
tags: [life]
---
#+END_HTML

* 《断舍离 瑜伽篇》

本来是冲着最近流行的“断舍离”找来这本书的，后来发现不是关于断舍离整理方法的，而是
《断舍离》作者山下英子和龙村修合著的关于倒是冲正弘（OKI MASAHIRO）的回忆录。本书
记录了冲正弘老师在冲道瑜伽修行法中点点滴滴智慧。

* 冲瑜伽的真谛

冲瑜伽并非完全以健康为目的，而是作为自我支柱、可以让人医生不断收益、“让人坚强地、
朝气蓬勃地活下去的人生真谛”。

在信息爆炸的时代保持坚强的自我支柱，我们最需要的是无论何时都能依靠、都能新来的强
大自我，具体来说，维护这样一个强大自我需要做到以下三点：

- 寻找既坚强又灵活的哲学
- 选择它作为自我支柱
- 以选定的自我支柱为基础，通过积累人生阅历，实现自我成长

* 生命即神

“生命本身就是神”是冲瑜伽哲学的核心。

另外“部分即全体”，“初学者应从形式入门”等观点也是冲瑜伽哲学的核心。山下英子就是从
这些观点中找到解决潜意识范围内的问题的线索，从而开发出断舍离理论。

冲瑜伽的本质目的是让人们坚强地走过人生旅程，实现坚定不移的自我成长。

* 培养一颗坚定不移的心

瑜伽是一种获取坚定不移信念的行为。

因为每个人都是独一无二的值得尊重的存在，因为人生是仅此一次的珍贵人生，所以我们才
能体会今天这一天、当下这一瞬间是多么珍贵和重要。我们必须领悟”对我们来说最重要的
是什么“，并在生活中重视它、付诸实践。

对自己真正必要的事物其实比我们想象的要少的多。

凡事都要冷静应对。

身体的姿势出现问题，就意味着生命这一自我的神明收到了损伤，反过来，让人呼吸顺畅、
神清气爽的姿势才能让生命充满喜悦。因此冲老师要求学员做出健康人的动作，不管学员是
生病的还是严重关节炎患者。

* 生存的力量就是做选择是的决断力

询问自己，对事物做出决断的力量就是一种活下去的力量。决断力也是可以训练提高的。如
果事事询问他人让人做决断的话，自己的决断力是毫无长进的。只有自己判断并做出行动，
才能磨炼自己的生存能力。

忽视自我判断，不以自我支柱为基础，而以他人为支柱进行判断，所以身心才会摇摆不定。
彻底地询问自己，反复这样的体验，便不再为他人所左右。

当人们注意到回答也可能千变万化的时候，就可以从自我的偏执，从不知不觉间形成的固定
思维，从特定的价值观中解脱出来。

一切都在变化。感受着变化的主体是自己的生命。意识到这样的可能性，我们的思维方式才
会获得解脱。而且，偏执和固有思维越少，越不会为琐事而动摇。

* 雅俗参半人生路

印度有一种”四住期“理论。认为人生可以划分为四个时期，最初 20 年是学生期，学习将来
如何在社会上立足。之后 20 年是家住期承担各种社会责任和义务，也就是世俗生活。家住
期之后是林住期，出家学习俗世中学不到的知识，开始专注于精神层面的提高。之后是游行
期，人们不再驻足某个地方，而是云游四方，彻底进入修行的生活状态。

要朝着自己选择的方向前进，明白什么对你是最有必要的。努力成为世界上第一无二的公司，
世界上第一的医生，厨师。

要敢于面对痛苦。冲老师说”病痛是神赐予的“。

对于感到厌恶的人，不要认为这个人是在给自己找麻烦，要认为这是神为了让自己进一步成
长，而特意派他来到自己的身边。

不论多么艰难的时期，也要认为”这是神赐予的一切“。因为人类的精神成长才是生存的意义，
困境才能让一个人得以成长。

生死都是神的旨意，人无能为力，但是健康确实人们可以触及的范围，对于维持健康应该竭
尽全力。

* 部分即全体，全体即部分

作为部分的人和全体的宇宙是关联的，部分的改变会影响全体，全体的变化也会影响部分。
基于这个理论，山下英子得出个人的物品与其潜意识的关系。观察人们摆放某个物品的理由，
或者是舍不得丢弃物品的理由，就会发现这几乎都是源自人际关系。

只有直面人际关系，才能找到最符合自己的生存的真谛和价值观。

* 学习体验冥想

一天睡几个小时的问题，根据不同的情况是不一样的，重要的是适合自己的身体。

通过”学习、体验、冥想“，边可以不拘细节，以更宏观的视野来审视事物。所学和所掌握的
知识的用途也会进一步拓展。所谓冥想就是俯瞰的视角。

练习瑜伽可以让身心保持平衡。

为了真正得到放松，在这之前需要让身体彻底紧张。

事物在举杯阴阳两面时才能取得平衡，并且阴阳之间存在调和的关系。

日本从古时候就有”八百万神明庇护“的俗语。日本人认为水也是神圣的，并且极力保持水的
清洁。饮用干净的税，心中会涌起感激的心情，浪费水或者将污水若无其事的排向大海则被
认为是羞耻的。

* 正确审视

“别轻信，别怀疑，只需亲身体验”

是否能正确审视事物，为了确认这一点，首先要逐一验证自己手中的信息。将自己手中的信
息的层面明确的分开，这是正确审视的第一步。哪些是单纯的信息，哪些是知识，哪些是智
慧。

“别自缚，别拘泥，别体谅”

不能彻底领悟和把握普遍性的真理，我们的心灵就无法得到真正的平静。

不丹人内心极其平静的。

明白自己的灵魂到底在追求什么，到底喜好什么，如果能认为某个工作是自己的天职，那么
他就能够专注于这份工作，而且专注于工作对他来说也是一件愉快的事情。

感到厌恶是改变自我的好机会。假设自己对某个事物怀有厌恶感。这时只要观察自己的内心，
就能发现这样的厌恶感其实来源于自己的某个价值观。究竟为什么会产生厌恶感？这是因为
他人的言行或外界和自己的价值观不一致。也就是说厌恶感不是外界的问题，而是内心的问
题，一切都是源自自己的感觉。

感到厌恶的时候坦然接受，将它视为重新审视自己价值观的契机，并通过冥想回顾过去就能
得到新的领悟。

自己周围所发生的一切，其实都是自己选择的结果。承担责任做出新的选择，以及不承担责
任而重复同样的事态，两种可能都取决于自己。

真正的为人着想，就不应该随意踏入他人做决断的范围内，为了他人能够按照自我的意志做
出决断就应当保持一定的距离。

* 鼓起勇气

人要从既定事实中好好吸取经验，增强自己的实力，凡事都要意志埋头苦干，奋勇前进。

尽人事，听天命，其中的重点在于自己是否真的“尽人事”了。未尽人事，也就是应该做的事
情没有尽力做好，反而偷懒的话，那理所当然，自己心中对结果的期待也只会一片灰暗。

归根结底，改变自我原本就是一件非常困难的事，却还希望靠别人来改变自我，显然是错误
的。必须由自己找到解决方案并付诸实践，终究还是要靠自己。

爱情既需要付出的勇气，也需要接受的勇气。

冲瑜伽的修行，分为 10 个过程。最初的阶段叫做”Yama（禁戒、禁止的意思）“和“Niyama
（劝诫、积极行事的意思）”。禁止做某事和积极行事，只有当两者共存的时候才能获得平
衡。

让身体处于最佳状态，只在最佳状态的时候工作，如果感觉疲劳就立刻结束工作。

人们应该积极的发散能量，并只接纳必需的能量。近年来罹患抑郁症的人非常多，其中的一
个原因就在于没有顺畅地发泄能量。在日常生活中拼命工作、发散能量的人，原本是不可能
患上抑郁症的。

看清自我是一件很恐怖的事。但是如果真能看清，心里就会轻松不少。因为没有必要对自己
撒谎。我并不是那么优秀，也不是那么差劲，我也不希望给别人那么优秀或者那么差劲的印
象，勇于接受真实的自我，才能保持这样坦然的态度。

改变外界和接受改变的勇气，最终都将拯救自己的生命。

困扰我们的问题，是源自过剩还是源自不足？对于这个问题，我想大多数人的原因都是能量
过剩。人际关系过剩和信息过剩等都体现在周围物品的堆积中。过剩本来就已经是严重的问
题，如果还多买几个箱子来收纳物品，那真的能够解决问题吗？

冲瑜伽修行的原则是别勉强，别浪费，坚持下去。而哲学原则是别轻信，别怀疑，只需亲身
体验。

印度瑜伽修行分为八个阶段：Yama（禁戒），Niyama（劝诫），Asana（动禅），
Puranayama（调气），Puratyahara（制感），Dharana（凝念），Dhyana（静虑），
Samadhi（三昧）。Samadhi 指石英社会生活。冲瑜伽增加了 Buddi（佛启）和
Purasado（法悦）。

冲老师提倡将神的喜悦、自我喜悦和社会的喜悦融为一体。

不管学到了多么高深的知识，如果不能再生活中灵活运用，那就只是一纸空谈。

现在的父母经常剥夺孩子的体验。“我很担心你”这句话的潜台词其实是“你要是一个人的话，
就什么也干不了”或者是“我不信任你”。“我是为了你好”这句话的潜台词是“我是为了我自己”。

充分散发能量后感到的疲劳，以及由于能量没能彻底发散而感到的疲劳，两者是完全不同的。

无视应该感恩的对象，无视应该感应的现象，这些都是麻痹。心一旦麻痹，就和死去没有区
别。

丹田最大的功效是让人们的精神保持平稳。不论何时都能有意识地保持冷静，做出正确的判
断。

冲瑜伽所有的训练都有一个共同的目的：在任何场合都能瞬间找回自己的意识，冷静地采取
最佳的应对措施。
