#+BEGIN_EXPORT html
---
layout: post
title: 意大利旅游申根签证（带小孩）
categories: [education]
tags: [travel]
---
#+END_EXPORT

终于弄好了意大利的旅游签证，因为是带着一个6岁的娃，所以手续相对麻烦一些。简单整
理如下，以供参考。

* 在哪里提交签证

首先，登录vfsglobal签证中心网站：
https://www.vfsglobal.cn/italy/china/chinese/index.html ，选择在哪个城市递交签证
申请，目前有北京、上海、广州和重庆市四个地方。我们离上海最近，因此选择上海。

* 选择签证类型

打开上海领区的页面后，选择签证类型：个人旅游（ADS除外）
https://www.vfsglobal.cn/italy/china/Shanghai/chinese/individul_tourism_visa_application.html

* 下载审核表

然后在所需材料标签页中找到“个人旅游签证申请审核表 （ADS除外） ”，这上面有意大利、
英语和中文的详细清单。签证受理专员也是按照这个清单一项项审核的。

* 准备签证资料

** 常规材料

*** 签证申请表

每人一份

在“表格下载”标签页中下载签证申请表
   （
   https://www.vfsglobal.cn/italy/china/Shanghai/chinese/pdf/Visa-application-Schengen-new-doc.pdf
   ），填写签证申请表。

*** 照片

每人两张

提交两张本人照片，ICAO规格，35mmx40mm，不要过度PS，6个月以内拍摄。不符合条件的话，
在签证中心。我家宝宝就是因为PS过度，看上去和真人不太像了，被要求重新拍摄。可以花
30元拍四张。

*** 护照

护照原件，确保回国日之后还有3个月有效期，有至少两张空白页。不然就赶紧更新护照。

复印护照首页和尾页，各两份。

如果有以往的申根签证，每个签证复印一页。

*** 户口本

每人一份。

复印户口本第一页开始到最后一页有信息的那一页为止。

*** 身份证

每人一份。

16岁以下没有身份证可以不提供。

*** 结婚证

夫妻两本各复印三分，大人小孩各一份。

** 行程计划

*** 旅行计划

每人一份。

模板地址：https://wenku.baidu.com/view/1363de89e73a580216fc700abb68a98271feacd6

显示城市、日期、交通、住宿等。涵盖出发与抵达之间的所有日期。

*** 往返机票

每人一份。

因为要提供英文版的机票预订单，携程、国航官网等都试了，不行。只有gotogate可以搞到：
https://www.gotogate.com/

在最后付款之前打印预订单。

*** 住宿证明

每人一份。

在Booking上切换语言为英文，预定可以免费取消的酒店：https://www.booking.com/

打印预订单。

** 在职、资产证明

*** 在职证明

父母各自每人一份，宝宝需要父母在职证明复印件各一份。

模板地址：https://wenku.baidu.com/view/14bbae6c2dc58bd63186bceb19e8b8f67d1cef2d

修改模板中名字、岗位、入职日期、公司、旅行起止日期、生日、护照号、公司地址等信息。
打印后，公司主管签字，盖公司章。

*** 名片

各提供一张。

*** 公司营业执照

父母各自每人一份，宝宝需要父母在职证明复印件各一份。

须盖公司章。

*** 银行流水

父母各自每人一份，宝宝需要父母在职证明复印件各一份。

储蓄卡3个月以上的资金记录。或者信用卡3月以上的对账单，加信用卡正面复印页。

*** 其他资产证明

房产证、机动车登记证、支付宝资产证明、股票账户投资资产证明等。


** 未成年小孩特别资料

*** 亲属关系公证书

原件及三份复印件。

可在线办理：https://www.hz-notary.com/ ，但是价格会翻倍。

有空的话最好现场办理，提供出生证、结婚证、身份证、户口本即可。费用为200到400元。

*** 小孩费用父母承担担保函原件

打印出来，父母签字。

模板：https://wenku.baidu.com/view/32933a43cd84b9d528ea81c758f5f61fb73628c5

* 提交给签证中心

杭州的签证中心在杭州市江干区钱江路1366号华润大厦7楼。需要到地下一层找到万象城门
口的保安登记获取门禁卡才能进去。

大人签证费469元。小孩子6周岁以下无需签证费，6周岁以上274元。服务费每个人78元。

快递每份护照单独邮寄，这个没办法。50元一份，非常坑。拍照一次30元，A4纸打印一次3
元，复印一次1元。护照状态更新短信通知15元每个人。这个可以选择不要，可以在签证中
心网站上自己查：https://www.vfsvisaonline.com/Global-PassportTracking/ 。不过速
度相当慢。
