#+BEGIN_EXPORT html
---
layout: post
title: 直白的英语
categories: [education]
tags: [English]
---
#+END_EXPORT

最近看了一本小书《Plain English Handbook》。这本书介绍如何用直白易懂的
英语写公司财报。虽然这书关注的是企业财务领域，但也能借鉴用于英语的日常
写作。

沃伦·巴菲特（Warren E. Buffett）写了序言：

#+begin_quote
When writing Berkshire Hathaway's annual report, I pretend that I'm
talking to my sisters. I have no trouble picturing them: Though highly
intelligent, they are not experts in accounting or finance. They will
understand plain English, but jargon may puzzle them. My goal is
simply to give them the information I would wish them to supply me if
our positions were reversed. To succeed, I don't need to be
Shakespeare; I must, though, have a sincere desire to inform.

我在写伯克希尔·哈撒韦公司年报的时候，我假想自己在和我的妹妹们谈天。我
很熟悉她们，所以很容易描述她们：虽然她们很聪明，但是她们不是会计财务方
面的专家。她们能理解直白英语，但是她们对财务术语犯懵。我的目标就是向她
们传达信息，然后相反地，她们也能将同样的信息传达给我。为此，我不需要成
为莎士比亚。但是我必须有强烈真诚的愿望去传达信息。
#+end_quote

我大概介绍这个小册子的要点，具体内容请查看：https://www.sec.gov/pdf/handbook.pdf

* 了解你的读者
了解读者是写作最重要的一个环节，只有了解他们，才可以有针对性的让他们理
解你的文章。

通过各种途径，了解他们：
- 年龄、教育水平、工作经验等
- 是否熟悉相关术语
- 他们如何读一份资料？通读还是先看重点？
- 他们读过以后，还会回头参考哪些章节？

为什么要了解读者呢？古希腊的亚里士多德说的很清楚：One must consider
also the audience...the reader is the judge.

* 理解你要传达的信息

写就初稿后，要仔细阅读，问自己这些问题：
- 我的读者理解我的表达方式吗？
- 我是否清楚传达了重要信息？
- 是否有哪些信息遗漏了？
- 有哪些信息重复冗余了？

* 调整文章顺序
1. 先进行概述，再进行详述
2. 用精简的语句设定层级章节标题
3. 把相关联的信息放在一起讨论

* 用直白的英语描写
虽然这个小册子叫《Plain English Handbook》，但其实前面讲的是一些重要的
基础。有了这些基础后，再用直白英语表达，就很完美了。

那么Plain English要注意什么呢？从反面来说，要避免以下情况：

1. 长句子。太长的句子，让人阅读的时候，换气困难，需要瞻前顾后才能领会
   意思。所以尽量拆分为简单的短句子。
2. 被动动词。被动句经常省略主语，让人猜测。不如改成主动句和主动词。
3. 否定词。not able 改成 unable，not accept 改成 reject等。
4. 多余的词。in order to 可以改为 to，in the event that 改成 if，
   subsequent to 改成 after。
5. 抽象词。比如 we made a determination... 可以改成 we determined...
6. 不常用的术语和暗语。
7. 不必要的细节
8. 最后，影响阅读的文档格式和排版。比如英语1.6倍行距，中文1.3倍行距。
   英语使用衬线字体等。
