#+BEGIN_HTML
---
layout: post
title: ABB自動化世界
categories: [technology]
tags: [industry]
---
#+END_HTML

ABB 自動化世界為期兩天，第一天開幕式，行業論壇＋晚宴，第二天幾十個 seminar 會場
同時進行。武漢會展中心 A 號展廳展出 ABB 最新的產品。

5 月 18 日早上五點半起牀散步到寶島公園回來吃好飯就搭上班車前往武漢國際展覽中心參
觀ABB自動化世界展覽。

*  開幕式
第一天的活動安排是 10 點開幕式，中國區CEO顧純元博士致開幕詞，CEO 史畢福（Ulrich
Spiesshofer）介紹 ABB 125 年發展歷史以及對中國經濟新常態的戰略規劃，武漢市副市長
劉立勇致辭，張斌博士演講主題《從製造到服務--中國經濟轉型與前景》。

** CEO Spiesshofer 主題演講《智能技術，智慧跨越》
因爲 ABB 主要業務是電力與自動化，所以 Spiesshofer 首先分析了全球電力系統的重大變
革：
- 電源結構調整：電源來源專項可再生能源，發電不穩不可預測，上網節點增多
- 輸配電：複雜化，控制信息越來越重要，輸電線路更長電壓更高
- 微網/納網結構發展

電力系統的變革動力是可再生能源、儲能、用電端連接、電力傳輸和自產自銷。

另外，自動化領域的重大變革由工業 3.0 向工業 4.0 發展，工業 4.0 的核心是物聯網+，
也就是 Internet of Thing, Service & People。

自動化領域的變革是更高的數據可用性、互聯互通以及高速增長的處理能力。

物聯網+的經典案例：
1. 前不久在漢諾威工業展上展示的利用智能傳感器遠程監測低壓電機的方案。 該方案減少
   了70％故障停工時間，減少了10％能源消耗，增加了30％使用期限；吸引了奧巴馬，默
   克爾同志的關注。
2. 與微軟攜手開發的電動汽車充電服務中心方案，將駕駛者，充電網絡運營商，支付商和
   合作伙伴相連。
3. 爲 140 艘馬士基集裝箱船提供導航優化軟件，根據船體設計以及天氣信息優化航線保障
   安全準時抵達

** 張斌《從製造到服務--中國經濟轉型與前景》

首先介紹了工業革命的國際經驗。工業革命的背後邏輯線索是：更大的市場規模 --> 更高
的專業化/生產效率 --> 更高的真實收入對更高級產品的需求/服務（亞當斯密） --> 更大
的市場規模。

根據發達國家以往的經驗，1990 國際元是經濟結構轉型的收入臨界點，美國，加拿大，英
國，法國，德國，日本在 1950 - 1970  年抵達。香港，台灣，韓國在 1981 - 1992 年達
到。中國在 2014 年附近接近臨界點。

*  行業論壇

開幕式結束后是七場行業論壇：
- ABB 助力石化企业实现可持续发展
- 从制造到智造：聚焦方案，技术对谈
- 为未来充电
- 打造从船到闸口的高效智慧港口
- 把握机遇   推动水行业可持续发展
- 可再生能源发展在中国的机遇与挑战
- “一带一路”—— 铁路发展与机遇

我參加了第一場行業論壇，由 ABB 過程自動化事業部 CEO Peter Terwiesch 主講，介紹了
公司在石油化工領域的解決方案。
