#+BEGIN_EXPORT html
---
layout: post
title: 瓦锡兰Wärtsilä海上浮动储能电池系统
categories: [technology]
tags: [energy]
---
#+END_EXPORT

因为参与了一些电池行业的业务，所以，开始关注储能系统，发布一些储能相
关咨询。

2021年3月11日储能网新闻，瓦锡兰集团的储能技术和系统集成业务部门在菲
律宾安装实施了一套大规模的海上飘浮电池储能系统，项目名为“floating
power barge”（飘浮能源驳船）。该项目在菲律宾Davao de Oro省，Maco地区，
配合Terma Marine公司（TMI）的100MW热电驳船，提供54MW/32MW储能容量。

Wärtsilä声称，该项目为TMI的内燃机发电系统，提供快速的电网辅助服务。
通过电池系统，将发电站的启动时间从15分钟缩短到3分钟。

项目于去年9月份启动，预期在今年第四季度交付。项目中会用到Wärtsilä公
司近期发布的Gridsolv Max储能解决方案，通过GEMS 能源管理系统和控制软
件平台进行能源管理。

瓦锡兰是为海事和能源市场提供智能科技和完整生命周期解决方案的全球领先
企业。瓦锡兰通过注重技术创新，总体效率以及数据分析，为客户的船舶和电
厂带来环境与经济性能最大化[fn:1]。

Wärtsilä在全球已经针对26个内燃机发电驳船，实施了1500MW储能系统。
而且Wärtsilä是目前唯一能提供驳船+储能系统+软件解决方案的公司。

Wärtsilä GridSolv Max标准化储能集装箱，内置了电池，安全系统，消防系
统，电力分发系统和空调系统。Wärtsilä GridSolv Max container is a
cost-effective energy storage solution. GridSolv Max significantly
increases energy density and system reliability for meeting customer
energy needs while also adequately future-proofing their hardware
assets. This innovative architecture simplifies installation and
integration across any energy storage application or deployment
size.

The standardised GridSolv Max storage enclosure consists of one ISO
40' unit and includes[fn:2]:
- Batteries
- Safety system
- Fire Safety System
- Power distribution
- Air conditioning system

Wärtsilä GEMS 能源管理系统集成了电池电力优化，单体电池控制和电池组控
制，远程监控，运维，诊断和安全可靠性服务等。Wärtsilä's sophisticated
GEMS energy management system is a smart software platform that
monitors, controls and optimises energy assets on both site and
portfolio levels.

GEMS supports a wide variety of battery and power electronics to
achieve optimal system performance. GEMS integrates and controls
individual resources and entire fleets comprising energy storage,
renewables and traditional thermal generation. Using machine
learning and historic and real-time data analytics to optimise the
asset mix, GEMS enables customers to remotely monitor, operate,
identify and diagnose equipment with unrivaled safety, reliability,
and flexibility[fn:3].

菲律宾国家由许多小岛组成，没有足够的土地建设发电站，因此浮动驳船发电
站+浮动驳船储能系统在当地有很好的应用场景。根据菲律宾政府统计，该国
可再生能源占比为：10.5%水电，13.4%地热，1%风电和光伏，0.4%生物能。

菲律宾国家能源部提出了NREP国家可再生能源计划，该项目目标在2030年实现
15GW可再生能源，其中地热增长75%，水电增长160%，同时实施2GW风电，和
284MW-1528MW光伏，从而达到50%-60%可再生能源利用比例。

* Footnotes

[fn:1] https://www.wartsila.cn

[fn:2] https://storage.wartsila.com/technology/gridsolv-max/

[fn:3] https://storage.wartsila.com/technology/gems/
