#+layout: post
#+title: SECS/SEM 半导体行业的工厂通信标准
#+categories: technology
#+tags: [industry]

不同的工业行业，都有数字化通信的需求。但是在发展之初，跨行业的沟通很少，
于是各行各业各自自行制定了各种不同的网络通信标准。比如之前介绍的注塑机
和 MES 通信的标准 [[http://kimi.im/2022-07-09-euromap77][EUROMAP 77]]。

同样的，在半导体行业，也有行业通行的通信标准，名叫 SECS/GEM。这个标准
是用于工厂主机系统（Factory Host System）和工业设备（Equipment）之间的
通信。

半导体设备发送数据、状态、事件、警报等信息给工厂主机系统，工厂就可以通
过工厂主机系统全方位监视和控制设备，实现生产的全自动化。

那么为什么这个标准叫这个奇奇怪怪的名字：SECS/GEM？

SECS 的全称是 Semiconductor Equipment Communication Standard。就是半导
体设备通信标准。而 GEM 的全称则是 Generic Equipment Model 通用设备模型。
工厂用来指导生产过程的 MES 系统，就可以通过这个通信和模型标准，来跟设
备进行顺畅通信了。

SECS/GEM 是一伙从事半导体行业的公司一起维护的标准。这样，大家开发的设
备和软件互相通信就不会出现鸡同鸭讲的问题了。

需要用到 SECS/GEM 的公司都有哪些呢？他们分别是：
- 做半导体生产设备的设备厂商
- 从事半导体生产的，半导体制造厂，晶圆制造厂
- 做表面贴装技术（Surface Mount Technology，SMT）设备的厂商
- 平板显示屏厂商
- 半导体产品测试设备厂商
- 半导体 MES 软件开发商

在 SECS/GEM 标准里，通信的双方又分为设备（Equipment）和主机（Host）。
设备呢，包含制程生产设备、厂务设备、终端等。主机（Host）呢，一般就是工
厂 IT 系统侧的 EAP、MES、CIM 等。

主机和设备之间都做哪些通讯呢？
- 远程设备通信和配置管理。GEM Semi-Bantu E30 部分用来处理这部分通信。
  包括数据采集，警报管理，设备配置，工艺上传下载，设备终端服务，本地远
  程控制等。
- SEMI E84 和 E87 部分管理上下料系统，比如说什么时间要给哪个设备提供哪
  些物料。
- SEMI E40 和 E94 处理任务管理。描述哪个设备在什么时间要处理哪些工艺。
  还要定义各个人物的物料清单和处理过程工艺。
- SEMI E10 用于监控分析设备工作性能，提供预测性维护、预测性停机、故障
  警告的根因分析等。
