#+LAYOUT: post
#+TITLE: 单边假设检验 One-Tailed Hypothesis Testing
#+TAGS: statistics,l6s
#+CATEGORIES: management
#+LATEX_HEADER: \usepackage{ctex}
#+LATEX_HEADER: \usepackage{amsmath}

有时候，我们只关心总体均值是否增大，则使用单边假设检验，分别有右边假设
检验和左边假设检验。

\[H_0 : \mu \leq \mu_0, ~~ H_1 : \mu > \mu_0\]

称为右边检验。

\[H_0 : \mu \geq \mu_0, ~~ H_1 : \mu < \mu_0\]

称为左边检验。

以下讨论单边检验的拒绝域。

设总体 \(X \sim N(\mu, \sigma^2)\), /\(\sigma\) 为已知，\(X_1, X_2,
\dots, X_n\) 是 \(X\) 的样本。求，给定显著性水平 \(\alpha\)下，检验问
题：

\[H_0 : \mu \leq \mu_0, ~~ H_1 : \mu > \mu_0\]

的拒绝域。

当 \(H_1\) 为真时，观察值的 \(\bar{x}\) 偏大，因此，拒绝域的形式为：

\[\bar{x} \geq k ~~ (\text{k 是某一正的常数})\]

\begin{align*}
P\{\text{当}H_0\text{为真拒绝}H_0\} &= P_{\mu \in H_0}\{\bar{X} \geq k\} \\
&= P_{\mu \leq \mu_0} \{ \frac{\bar{X} - \mu_0}{\sigma / \sqrt{n}} \geq \frac{k - \mu_0}{\sigma / \sqrt{n}} \} \\
&\leq P_{\mu \leq \mu_0} \{ \frac{\bar{X} - \mu}{\sigma / \sqrt{n}} \geq \frac{k - \mu_0}{\sigma / \sqrt{n}}\}
\end{align*}

要控制 \(P\{\text{当}H_0\text{为真拒绝}H_0\}\) 在 \(\alpha\) 范围内，只需令

\[P_{\mu \leq \mu_0} \{ \frac{\bar{X} - \mu}{\sigma / \sqrt{n}} \geq \frac{k - \mu_0}{\sigma / \sqrt{n}}\} = \alpha\]

由于


\[ \frac{\bar{X} - \mu}{\sigma / \sqrt{n}} \sim N(0, 1) \]

得到

\[ \frac{k - \mu_0}{\sigma / \sqrt{n}} = z_\alpha\]

于是

\[ k = \mu_0 + \frac{\sigma}{\sqrt{n}} z_\alpha\]

即得到，检验问题的拒绝域为

\[ \bar{x} \geq \mu_0 + \frac{\sigma}{\sqrt{n}} z_\alpha\]

即

\[ z = \frac{\bar{x} - \mu_0}{\sigma / \sqrt{n}} \geq z_\alpha\]

类似的，可以得到左边检验问题

\[ H_0 ： \mu \geq \mu_0, ~~ H_1 : \mu < \mu_0\]

的拒绝域为

\[ z = \frac{\bar{x} - \mu_0}{\sigma / \sqrt{n}} \leq - z_\alpha\]

试举一例。某工厂生产的元器件寿命不低于 1000 小时，现在随机抽取样品 25
件，测得其寿命分别为 950, 920, 970, 949, 920, 920, 955, 950, 990, 910,
920, 950, 911, 956, 1019, 930, 890, 980, 1020, 990。已知该元器件寿命服
从标准差 \(\sigma = 100 \) 小时的正态分布。试在显著性水平 \(\alpha =
0.05 \) 下判断这批元器件是否合格。

*解*

按照题意，需要检验左边检验假设：

\[ H_0 : \mu \geq \mu_0 = 1000\] 认为合格

\[ H_1 : \mu < \mu_0 \] 认为不合格

#+header: :output-dir images :file R-norm-one-tailed.svg
#+begin_src R :results file graphics :eval no-export :exports both
library(rcompanion)
data <- c(950, 920, 970, 949, 920, 920, 955, 950, 990, 910, 920,
          950, 911, 956, 1019, 930, 890, 980, 1020, 990)
qqnorm(data)
qqline(data, col="red") 
#+end_src

#+RESULTS:
[[file:images/R-norm-one-tailed.svg]]

#+begin_src R :results output :exports both
library("BSDA")
data <- c(950, 920, 970, 949, 920, 920, 955, 950, 990, 910, 920,
          950, 911, 956, 1019, 930, 890, 980, 1020, 990)
z.test(x = data,
       alternative = "less",
       mu = 1000, sigma.x = 100,
       conf.level = 0.95)
#+end_src

#+RESULTS:
#+begin_example

	One-sample z-Test

data:  data
z = -2.2361, p-value = 0.01267
alternative hypothesis: true mean is less than 1000
95 percent confidence interval:
     NA 986.78
sample estimates:
mean of x 
      950 

#+end_example

p-value 小于 0.05, 所以，我们在显著性水平 \(\alpha = 0.05 \) 下，拒绝
\(H_0\), 即认为这批产品不合格。
