#+LAYOUT: post
#+TITLE: 边缘计算新标准 Margo：技术术语
#+TAGS: industry
#+CATEGORIES: industry

Linux 基金会近日联合 ABB，B&R，Capgemini，微软，罗克韦尔自动化，施耐德
电气，以及西门子，发起了一个新的[[./2024-05-16-margo][开放标准项目 Margo]] 。目的是定义一套灵
活、简单、易扩展的边缘接口标准。通过边缘编排软件，把边缘应用和边缘设备
进行有效的管理起来。

之后，我介绍了 Margo [[./2024-05-19-margo-edge-device][对边缘计算设备的一些要求]]。

今天再补充一下相关的基本概念。

*边缘应用（Application）*

边缘应用适配边缘计算设备的特定应用。边缘应用的组成部分包括：应用声明文
件、应用描述文件、若干个容器。这些容器可以部署到若干个边缘计算节点上。

*边缘计算设备（Edge Compute Device）*

安装在用户现场、可运行 Margo 应用的边缘计算硬件设备。设备部署到现场后，
根据其能力分成多个角色：
- 独立集群服务器
- 集群主节点
- 集群工作从节点
- 独立设备
- 嵌入式微设备

*工作负载编排软件（Workload Orchestration Software，简称 WOS）*

系统服务，帮助用户配置、部署、管理边缘应用。通过 Margo 标准接口与应用
仓库、设备仓库通信，并编排边缘计算节点。

*工作负载编排代理（Workload Orchestration Agent）*

运行在边缘计算设备中的服务，用于和工作负载编排软件通信，接收工作负载和配置数据。

*设备编排软件（Device Orchestration Software）*

用于部署、删除、维护边缘计算设备。与工作负载编排软件一起，给用户提供边缘计算管理功能。

*设备编排代理（Device Orchestration Agent）*

运行在边缘计算设备中的服务，用于和设备编排软件通信，接收设备配置数据，
并加载到边缘计算设备中。

*应用登记仓库（Application Registry）*

边缘应用开发人员搭建的资料仓库，存放应用声明和应用市场相关资料。

*应用仓库（Application Repository）*

编排软件从应用仓库获取应用资料，部署到边缘计算设备。

*应用市场（Application Marketplace）*

用户在应用市场，从应用厂商购买应用的使用权。
- 展示可购买的应用清单
- 用户可购买应用使用权限
- 提供应用相关信息，可以获取应用文件资料

*应用类目（Application Catalog）*

在工作负载编排软件中列出的可供用户部署和管理的应用清单。也就是从应用市
场中购买了应用权限的应用。
