#+BEGIN_HTML
---
layout: post
title: 管理技能：行为面试法
categories: [leadership]
tags: [management]
---
#+END_HTML

最近又招聘新员工了，查阅一份份简历，一个个打电话约谈，大海淘沙般挑选最合适的团队
成员。这时候该拿出好久前学到的行为面试法来复习复习了。

* 行为面试法

行为面试法（BBI, Behavioural Based Interview）也叫关键行为面试法（CBI, Critical
Behaviour Interview）是通过要求面试对象描述其过去某个工作或者生活经历的具体情况
来了解面试对象各方面素质特征的方法。

行为面试法的基本假设是：通过一个人过去相似情况下的行为可以预测这个人将来的行为。
（the most accurate predictor of future performance is past performance in a
similar situation.）

传统的面试方法容易导致被试者信口开河发挥想象去迎合面试者的期望听到的：“加班，没
问题！周末加班，需要的话也不是问题！长期出差，我的最爱！”

而行为面试法要求被试者描述已经发生的事情，在当时的情形，自己是如何处理应对的。因
此是基于事实的询问，被试者无法随意夸张信口开河。

这里又要提一下孔子的经典论断：“視其所以，觀其所由，察其所安，人焉廋哉？人焉廋
哉？”详见上一篇文章[[http://kimi.im/2016-08-03-versatile-communication][管理技能：溝通中的迎合能力]]。

* 行为面试法基本步骤

行为面试法主要有三个步骤：

1. 互相介绍和解释
2. 了解工作与职责
3. 具体事件的询问

步骤一，互相介绍和解释。先进行互相介绍，旨在建立面试者和被试者之间的信任关系，创
造融洽的谈话气氛，使被试者感到放松，并愿意讲出自己的经历。同时解释面试的保密性原
则。时间大概是 3 分钟左右。

步骤二，了解工作与职责。通过简单的提问了解被试者目前的头衔，工作内容，工作职责，
项目经历，技术特长，性格特征等。这一步骤的目的是为后续详细提问收集突破口。比如参
与过哪些重大的项目，负责过哪个技术的难点攻克，具备哪些优秀的品质等。这一步骤大概
持续 5 分钟左右。

步骤三，具体事件的询问。通过对具体时间的询问，让被试者讲述事件发生的情景，任务，
所发生的行为，以及事件最终的结果。就是所谓的 STAR 方法。

* STAR 方法

STAR 方法是一种结构化的行为面试提问法，有如下四个方面组成：[fn:1]
- S（Situation that existed) ）事件发生的时间、地点和涉及到的人员
- T（Task or problem to be undertaken）要完成的任务或遇到的问题
- A（Action taken by yourself）自己采取了哪些步骤或行动
- R（Result what happened）得出了什么样的结果，取得了什么成就

这四个方面内容缺一不可，必须完整。

其实反过来说，STAR 也是被试者在面试过程中回答问题的顺序方法。

* 实际案例分析

接下来，一起看看今天面试遇到的几个 STAR 情景吧。

** 做事严谨，追求卓越

面试过一个年轻人，他在自我评价中写自己做事严谨。

我的提问：可不可以告诉我你觉得哪一件事情当中最能体现你做事严谨的风格？

被试者的回答：之前在一家公司开发了一个应用程序，但是由于项目任务紧，程序代码结构
不够优化，没有做到模块之间的松耦合，但是程序已经冻结上线了（Situation）。为了更
好的掌握优秀代码结构的开发（Task），我利用自己的业余时间重新实现了一遍该程序的功
能（Action）。重新设计的程序代码结构耦合性很好，独立模块的改动不会影响主程序
（Result）。

这个 STAR 情景描述了被试者做事有始有终，尽管项目工作已经结束，依然不懈努力追求卓
越的品性。

** 坚韧不拔，不轻易放弃

另一个年轻人则称自己有坚韧不拔，不轻易放弃的品质。

我的提问：讲一讲最能体现你坚韧不拔的一件事情？

被试者的回答：在其开发的一款产品遇到噪声很大的问题，经过多次尝试，很多同事已经决
定放弃的情况下（Situation）。为了确保提交高质量的产品（Task），我一个人持续在现
场调试控制算法一个多月（Action），最终把噪音问题解决（Result）。

* 总结

面试者可以通过行为面试法中的 STAR 方法获得被试者在特定情境下的行为事实，从而可以
分析其行为背后的内在品质，从而推测被试者在未来相似情境下行为选择；基于这些判断，
选择合适的候选人。

所以为了确保顺利完成招聘任务，我要不断的熟悉 STAR 方法的运用，提高自己鉴别人才的
能力。

* Footnotes

[fn:1] http://careers.ls.wisc.edu/documents/STAR_Method_for_Behavioral_Interview_Questions_8.12.pdf
