#+BEGIN_HTML
---
layout: post
title: 管理技能：溝通中的迎合能力
categories: [leadership]
tags: [communication]
---
#+END_HTML

出差來上海參加爲期五天的管理能力培訓。

白天上課強度還是挺大的：知識點學習，案例分析，小組討論，即興演講，等等活動都要積
极參與，注意力高度集中，大腦飛速運轉，能力迅速提升。

晚上的複習工作必須不能少，不然到第二天腦子裏殘留的東西會迅速減少，數日之後，殘存
的記憶就更少了。

* 迎合能力

第一天課的主題是溝通中的迎合能力，又叫應變能力，權變能力，適應能力。其實稱之爲人
際交往中的權變能力更恰當。不過教材是這麼翻譯的，就權且這麼稱呼它吧。

Wilson Learning 網站上是這麼定義迎合能力的：[fn:1]

#+BEGIN_QUOTE
Versatility[fn:2] is defined as the ability to understand differences in
communication preferences and to adapt to make others more open and receptive —
creating more effective and productive relationships.
#+END_QUOTE

迎合能力是一種理解溝通習慣差異，並調整自己與他人溝通的方式，從而使他人更願意接納
你的觀點，從而提高人際關係的效率和產出的能力。

根據我的上司、同事和下屬的課前測評來看，我的迎合能力處在中等偏下水平，有許多值得
改進的地方。因此，這一天的課，對我來說是非常重要的。

* 迎合能力靈活應變模型

迎合能力具體的操作方法可歸納爲 IAA：識別（Identify），分析（Analyze），調整（Adjust）。

** 識別

識別溝通對方的社交風格：

- 主張方式（Assertiveness）是命令導向（Tell-Directed）還是詢問導向（Ask-Directed）
- 迴應方式（Responsiveness）是任務導向（Task-Directed）還是人際導向
  （People-Directed）

下圖根據主張方式和迴應方式將社交風格氛圍四個主要類型：

#+BEGIN_HTML
<svg xmlns="http://www.w3.org/2000/svg" xmlns:p="http://www.evolus.vn/Namespace/Pencil" xmlns:pencil="http://www.evolus.vn/Namespace/Pencil" xmlns:html="http://www.w3.org/1999/xhtml" xmlns:xhtml="http://www.w3.org/1999/xhtml" xmlns:office="urn:oasis:names:tc:opendocument:xmlns:office:1.0" xmlns:style="urn:oasis:names:tc:opendocument:xmlns:style:1.0" xmlns:text="urn:oasis:names:tc:opendocument:xmlns:text:1.0" xmlns:table="urn:oasis:names:tc:opendocument:xmlns:table:1.0" xmlns:draw="urn:oasis:names:tc:opendocument:xmlns:drawing:1.0" xmlns:fo="urn:oasis:names:tc:opendocument:xmlns:xsl-fo-compatible:1.0" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:meta="urn:oasis:names:tc:opendocument:xmlns:meta:1.0" xmlns:number="urn:oasis:names:tc:opendocument:xmlns:datastyle:1.0" xmlns:svg="urn:oasis:names:tc:opendocument:xmlns:svg-compatible:1.0" xmlns:chart="urn:oasis:names:tc:opendocument:xmlns:chart:1.0" xmlns:dr3d="urn:oasis:names:tc:opendocument:xmlns:dr3d:1.0" xmlns:math="http://www.w3.org/1998/Math/MathML" xmlns:form="urn:oasis:names:tc:opendocument:xmlns:form:1.0" xmlns:script="urn:oasis:names:tc:opendocument:xmlns:script:1.0" xmlns:ooo="http://openoffice.org/2004/office" xmlns:ooow="http://openoffice.org/2004/writer" xmlns:oooc="http://openoffice.org/2004/calc" xmlns:dom="http://www.w3.org/2001/xml-events" xmlns:xforms="http://www.w3.org/2002/xforms" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:rpt="http://openoffice.org/2005/report" xmlns:of="urn:oasis:names:tc:opendocument:xmlns:of:1.2" xmlns:rdfa="http://docs.oasis-open.org/opendocument/meta/rdfa#" xmlns:field="urn:openoffice:names:experimental:ooo-ms-interop:xmlns:field:1.0" xmlns:regexp="http://exslt.org/regular-expressions" xmlns:em="http://exslt.org/math" xmlns:sodipodi="http://sodipodi.sourceforge.net/DTD/sodipodi-0.dtd" xmlns:inkscape="http://www.inkscape.org/namespaces/inkscape" width="744.09448819" height="1052.3622047" id="exportedSVG" version="1.1" pencil:version="1.2.2" sodipodi:docname="SocialStyle"><g inkscape:label="Untitled Page" inkscape:groupmode="layer" id="layer_untitled_page"><g><rect x="0" y="0" width="452" height="452" fill="none"/><g p:type="Shape" p:def="Evolus.Common:RoundedRectV2" id="5f0897519e454f37829955a548307bc3" transform="matrix(1,0,0,1,116,84)"><p:metadata><p:property name="box">218,193</p:property><p:property name="withBlur">false</p:property><p:property name="radius">0,0</p:property><p:property name="textPadding">0,24.125</p:property><p:property name="fillColor">#FFFFFFFF</p:property><p:property name="strokeColor">#1B3280FF</p:property><p:property name="strokeStyle">2|</p:property><p:property name="textContent">
                </p:property><p:property name="textFont">"Liberation Sans",Arial,sans-serif|normal|normal|13px|none</p:property><p:property name="textColor">#000000FF</p:property><p:property name="textAlign">1,1</p:property></p:metadata>

            <defs>
                <rect width="216" height="191" rx="0" ry="0" x="0" y="0" style="stroke-width: 2; fill: rgb(255, 255, 255); fill-opacity: 1; stroke: rgb(27, 50, 128); stroke-opacity: 1;" p:name="rrRect" id="ae18591b3d40442baf4d30b7f5178759" transform="translate(1,1)"/>
                <filter height="1.2558399" y="-0.12792" width="1.06396" x="-0.03198" p:name="shadingFilter" id="0fb6e38d22d44d9f9afde3661058206a">
                    <feGaussianBlur stdDeviation="1" in="SourceAlpha"/>
                </filter>
                <clipPath p:name="textClipPath" id="8d78d1a11bbb4454a8fe36d4bcf020f1">
                    <rect p:name="textClipPathRect" id="85d056c077854977b57b5f15b5cc46df" x="24.125" y="24.125" width="169.75" height="144.75"/>
                </clipPath>
            </defs>
            <use xlink:href="#ae18591b3d40442baf4d30b7f5178759" transform="translate(2, 2)" p:filter="url(#0fb6e38d22d44d9f9afde3661058206a)" style="opacity: 0.5; visibility: hidden; display: none;" p:heavy="true" p:name="bgCopy" id="798a8df070a84883bd1e4d34ff087596"/>
            <use xlink:href="#ae18591b3d40442baf4d30b7f5178759"/>
            <g clip-path="url(#8d78d1a11bbb4454a8fe36d4bcf020f1)" p:name="text" id="23efe3c5725c454cbcd481e82a6a9b1a" dominant-baseline="auto" style="font-family: &quot;Liberation Sans&quot;, Arial, sans-serif; font-size: 13px; font-weight: normal; font-style: normal; text-decoration: none; fill: rgb(0, 0, 0); fill-opacity: 1; color: rgb(0, 0, 0); opacity: 1;"><g transform="translate(0,60)"><text/></g></g>
        </g><g p:type="Shape" p:def="Evolus.Common:Line" id="825fff62f3f64346bc90a9c2e36949a4" transform="matrix(1,0,0,1,96,175)"><p:metadata><p:property name="box">259,10</p:property><p:property name="strokeColor">#1B3280FF</p:property><p:property name="strokeStyle">2|</p:property></p:metadata>
            <rect style="fill: #000000; fill-opacity: 0; stroke: none;" x="0" y="0" p:name="bgRect" id="cf408740b87c493fb0e2a5404f5cabee" width="259" height="10"/>
            <path style="fill: none; stroke: rgb(27, 50, 128); stroke-width: 2; stroke-opacity: 1;" d="M 0 5 L 259 5" p:name="line1" id="061d2ff0969348f78998fd82f5741840" transform="translate(0,0)"/>
        </g><g p:type="Shape" p:def="Evolus.Common:Line" id="04dea28ccfe14c5e9a4ae8fbf992f74d" transform="matrix(6.123233601181349e-17,1,-1,6.123233601181349e-17,230.5,50.5)"><p:metadata><p:property name="box">259,10</p:property><p:property name="strokeColor">#1B3280FF</p:property><p:property name="strokeStyle">2|</p:property></p:metadata>
            <rect style="fill: #000000; fill-opacity: 0; stroke: none;" x="0" y="0" p:name="bgRect" id="4c025fcf7be44c40969b37b45a8a3c20" width="259" height="10"/>
            <path style="fill: none; stroke: rgb(27, 50, 128); stroke-width: 2; stroke-opacity: 1;" d="M 0 5 L 259 5" p:name="line1" id="5c5b638029e141cdb6db5f5569988a38" transform="translate(0,0)"/>
        </g><g p:type="Shape" p:def="Evolus.Common:RichTextBoxV2" id="153fcf91c7dd4f3584cfb8dbf6aa3e17" transform="matrix(1,0,0,1,177,5)"><p:metadata><p:property name="width">200,0</p:property><p:property name="fixedWidth">false</p:property><p:property name="textContent">&lt;div xmlns="http://www.w3.org/1999/xhtml" style="text-align: center;"&gt;&lt;span style="line-height: 1.1;"&gt;Task-Directed&lt;/span&gt;&lt;/div&gt;&lt;div xmlns="http://www.w3.org/1999/xhtml" style="text-align: center;"&gt;&lt;span style="line-height: 1.1;"&gt;Responsiveness&lt;/span&gt;&lt;/div&gt;</p:property><p:property name="textFont">"Liberation Sans",Arial,sans-serif|normal|normal|13px|none</p:property><p:property name="textColor">#000000FF</p:property><p:property name="customStyle">
                </p:property></p:metadata>

            <foreignObject x="0" y="0" width="96" height="36" p:name="htmlObject" id="600fd0ba1d4d427890ef3e095c286908" style="color: rgb(0, 0, 0); opacity: 1; font-family: &quot;Liberation Sans&quot;, Arial, sans-serif; font-size: 13px; font-weight: normal; font-style: normal; text-decoration: none;">
                <div xmlns="http://www.w3.org/1999/xhtml" p:name="textDiv" id="9d9ccbc93e1a4fa78968bab0d063dadb" style="display: inline-block; white-space: nowrap; text-decoration: none;"><div><div style="text-align: center;"><span style="line-height: 1.1;">Task-Directed</span></div><div style="text-align: center;"><span style="line-height: 1.1;">Responsiveness</span></div></div></div>
            </foreignObject>
        </g><g p:type="Shape" p:def="Evolus.Common:RichTextBoxV2" id="5a954b0bc1e44dc1a0b6391d0180c491" transform="matrix(1,0,0,1,177,319)"><p:metadata><p:property name="width">200,0</p:property><p:property name="fixedWidth">false</p:property><p:property name="textContent">&lt;div xmlns="http://www.w3.org/1999/xhtml" style="text-align: center;"&gt;&lt;span style="line-height: 1.1;"&gt;People-Directed&lt;/span&gt;&lt;/div&gt;&lt;div xmlns="http://www.w3.org/1999/xhtml" style="text-align: center;"&gt;&lt;span style="line-height: 1.1;"&gt;Responsiveness&lt;/span&gt;&lt;/div&gt;</p:property><p:property name="textFont">"Liberation Sans",Arial,sans-serif|normal|normal|13px|none</p:property><p:property name="textColor">#000000FF</p:property><p:property name="customStyle">
                </p:property></p:metadata>

            <foreignObject x="0" y="0" width="96" height="36" p:name="htmlObject" id="d5730e23b6414387af11c558d48b946c" style="color: rgb(0, 0, 0); opacity: 1; font-family: &quot;Liberation Sans&quot;, Arial, sans-serif; font-size: 13px; font-weight: normal; font-style: normal; text-decoration: none;">
                <div xmlns="http://www.w3.org/1999/xhtml" p:name="textDiv" id="2baec96934fd425298460c7d0e29dc20" style="display: inline-block; white-space: nowrap; text-decoration: none;"><div><div style="text-align: center;"><span style="line-height: 1.1;">People-Directed</span></div><div style="text-align: center;"><span style="line-height: 1.1;">Responsiveness</span></div></div></div>
            </foreignObject>
        </g><g p:type="Shape" p:def="Evolus.Common:RichTextBoxV2" id="19dcd8f4b8014c4ab67b9d572d45a95c" transform="matrix(1,0,0,1,364,162)"><p:metadata><p:property name="width">200,0</p:property><p:property name="fixedWidth">false</p:property><p:property name="textContent">&lt;div xmlns="http://www.w3.org/1999/xhtml" style="text-align: center;"&gt;Tell-Directed&lt;br /&gt;Assertiveness&lt;/div&gt;</p:property><p:property name="textFont">"Liberation Sans",Arial,sans-serif|normal|normal|13px|none</p:property><p:property name="textColor">#000000FF</p:property><p:property name="customStyle">
                </p:property></p:metadata>

            <foreignObject x="0" y="0" width="83" height="36" p:name="htmlObject" id="04a50dadf0d24f16bade71fef807c1a6" style="color: rgb(0, 0, 0); opacity: 1; font-family: &quot;Liberation Sans&quot;, Arial, sans-serif; font-size: 13px; font-weight: normal; font-style: normal; text-decoration: none;">
                <div xmlns="http://www.w3.org/1999/xhtml" p:name="textDiv" id="bb911aff364c4fbba4258e24944413c8" style="display: inline-block; white-space: nowrap; text-decoration: none;"><div><div style="text-align: center;">Tell-Directed<br />Assertiveness</div></div></div>
            </foreignObject>
        </g><g p:type="Shape" p:def="Evolus.Common:RichTextBoxV2" id="126164fff11f4e18949f525a91623590" transform="matrix(1,0,0,1,5,162)"><p:metadata><p:property name="width">200,0</p:property><p:property name="fixedWidth">false</p:property><p:property name="textContent">&lt;div xmlns="http://www.w3.org/1999/xhtml" style="text-align: center;"&gt;Ask-Directed&lt;br /&gt;Assertiveness&lt;/div&gt;</p:property><p:property name="textFont">"Liberation Sans",Arial,sans-serif|normal|normal|13px|none</p:property><p:property name="textColor">#000000FF</p:property><p:property name="customStyle">
                </p:property></p:metadata>

            <foreignObject x="0" y="0" width="83" height="36" p:name="htmlObject" id="7bce78fd487843fb94298f2959be9617" style="color: rgb(0, 0, 0); opacity: 1; font-family: &quot;Liberation Sans&quot;, Arial, sans-serif; font-size: 13px; font-weight: normal; font-style: normal; text-decoration: none;">
                <div xmlns="http://www.w3.org/1999/xhtml" p:name="textDiv" id="26a3a937acfa42dbbc0866bb75979bc5" style="display: inline-block; white-space: nowrap; text-decoration: none;"><div><div style="text-align: center;">Ask-Directed<br />Assertiveness</div></div></div>
            </foreignObject>
        </g><g p:type="Shape" p:def="Evolus.Common:RichTextBoxV2" id="fa9160782b5941d3a24cf6a45df49b01" transform="matrix(1,0,0,1,262,125)"><p:metadata><p:property name="width">200,0</p:property><p:property name="fixedWidth">false</p:property><p:property name="textContent">&lt;div xmlns="http://www.w3.org/1999/xhtml" style="text-align: center;"&gt;&lt;span style="font-weight: bold;"&gt;Driver&lt;/span&gt;&lt;/div&gt;</p:property><p:property name="textFont">"Liberation Sans",Arial,sans-serif|normal|normal|13px|none</p:property><p:property name="textColor">#FF9900FF</p:property><p:property name="customStyle">
                </p:property></p:metadata>

            <foreignObject x="0" y="0" width="37" height="18" p:name="htmlObject" id="488154346eb243ab8138cbe512458686" style="color: rgb(255, 153, 0); opacity: 1; font-family: &quot;Liberation Sans&quot;, Arial, sans-serif; font-size: 13px; font-weight: normal; font-style: normal; text-decoration: none;">
                <div xmlns="http://www.w3.org/1999/xhtml" p:name="textDiv" id="623912a7b71f4e84926f99c67d1cbaa5" style="display: inline-block; white-space: nowrap; text-decoration: none;"><div><div style="text-align: center;"><span style="font-weight: bold;">Driver</span></div></div></div>
            </foreignObject>
        </g><g p:type="Shape" p:def="Evolus.Common:RichTextBoxV2" id="2b7382ff22a0475e99bfde593a832153" transform="matrix(1,0,0,1,247,221)"><p:metadata><p:property name="width">200,0</p:property><p:property name="fixedWidth">false</p:property><p:property name="textContent">&lt;div xmlns="http://www.w3.org/1999/xhtml" style="text-align: center;"&gt;&lt;span style="font-weight: bold;"&gt;Expressive&lt;/span&gt;&lt;/div&gt;</p:property><p:property name="textFont">"Liberation Sans",Arial,sans-serif|normal|normal|13px|none</p:property><p:property name="textColor">#FF0000FF</p:property><p:property name="customStyle">
                </p:property></p:metadata>

            <foreignObject x="0" y="0" width="68" height="18" p:name="htmlObject" id="c93947b0133a4c268b932e33116131aa" style="color: rgb(255, 0, 0); opacity: 1; font-family: &quot;Liberation Sans&quot;, Arial, sans-serif; font-size: 13px; font-weight: normal; font-style: normal; text-decoration: none;">
                <div xmlns="http://www.w3.org/1999/xhtml" p:name="textDiv" id="ab5a8bd7efc247cc8791efa0aa825a5f" style="display: inline-block; white-space: nowrap; text-decoration: none;"><div><div style="text-align: center;"><span style="font-weight: bold;">Expressive</span></div></div></div>
            </foreignObject>
        </g><g p:type="Shape" p:def="Evolus.Common:RichTextBoxV2" id="6dd07ec08e2f430f8d680fbbf2796a70" transform="matrix(1,0,0,1,145,221)"><p:metadata><p:property name="width">200,0</p:property><p:property name="fixedWidth">false</p:property><p:property name="textContent">&lt;div xmlns="http://www.w3.org/1999/xhtml" style="text-align: center;"&gt;Amiable&lt;/div&gt;</p:property><p:property name="textFont">Arial|bold|normal|13px|none</p:property><p:property name="textColor">#009900FF</p:property><p:property name="customStyle">
                </p:property></p:metadata>

            <foreignObject x="0" y="0" width="51" height="18" p:name="htmlObject" id="ab320d94b2d44b54b782fff4f61a7ddf" style="color: rgb(0, 153, 0); opacity: 1; font-family: Arial; font-size: 13px; font-weight: bold; font-style: normal; text-decoration: none;">
                <div xmlns="http://www.w3.org/1999/xhtml" p:name="textDiv" id="e4499ec4fa3e4d0d96434ad8fbe9f275" style="display: inline-block; white-space: nowrap; text-decoration: none;"><div><div style="text-align: center;">Amiable</div></div></div>
            </foreignObject>
        </g><g p:type="Shape" p:def="Evolus.Common:RichTextBoxV2" id="5be6a1cd483f41af938e726b5fbf4025" transform="matrix(1,0,0,1,140,125)"><p:metadata><p:property name="width">200,0</p:property><p:property name="fixedWidth">false</p:property><p:property name="textContent">&lt;div xmlns="http://www.w3.org/1999/xhtml" style="text-align: center;"&gt;Analytical&lt;/div&gt;</p:property><p:property name="textFont">Arial|bold|normal|13px|none</p:property><p:property name="textColor">#3333FFFF</p:property><p:property name="customStyle">
                </p:property></p:metadata>

            <foreignObject x="0" y="0" width="61" height="18" p:name="htmlObject" id="07d8ffe4651a4084932381c05b563d1d" style="color: rgb(51, 51, 255); opacity: 1; font-family: Arial; font-size: 13px; font-weight: bold; font-style: normal; text-decoration: none;">
                <div xmlns="http://www.w3.org/1999/xhtml" p:name="textDiv" id="48fbbaafce964d79ae262761d734ff2f" style="display: inline-block; white-space: nowrap; text-decoration: none;"><div><div style="text-align: center;">Analytical</div></div></div>
            </foreignObject>
        </g></g></g></svg>
#+END_HTML

我順便在上圖四象限中做了四種顏色標記，我把樂嘉所謂的性格色彩學[fn:3]也映射到社交
風格類型中。四種性格顏色是這麼定義的：
- 紅色：“元氣族”，快樂外向的團隊帶動者，做事情的動機很大程度上是爲了快樂，隨性而又善於交際。
- 藍色：“心機蛇”，最佳執行官，過度認真，善於分析。
- 黃色：“山林之王”，強有力的激進指揮者。深層次的驅動力來自對目標的實現和完成。
- 綠色：“和事佬”，和平的促進者，追求和諧穩定，適應性強，很好的傾聽者。

兩種分類模型側重點不同，但是還是有不少的重合。姑且組合着用吧。

有以上兩種識別社交風格和性格特徵的參考指標之後，就可以通過觀察、試探等多種方法去
識別溝通對方的社交風格和性格類型了。

這裏我想順便提一提老祖宗孔子在《論語》中提到的一句經典論斷：“視其所以，觀其所由，
察其所安，人焉廋哉？人焉廋哉？”

這句話很好的總結了看人識人的方法學。我們在考察人的時候，要先觀察他做事情的原因是
什麼，他的動機是什麼；然後再觀察他做事情的途徑方法是什麼，他是怎麼去解決問題的；
最後再深入的考察他做事情的內心狀態是如何的，他是不是心安於所做的事情。如此層層深
入的去探究一個人，那麼他哪還怎麼可能藏匿自己呢？

這種系統的考察人的動機、行爲和心理的方法還是很值得借鑑的。

** 分析 & 調整

在識別了溝通對象的社交風格之後，就要分析對方的期望和反感，再根據自己的風格類型，
跳出自己的舒適區，像對方的社交風格舒適區邁進，做出相應的調整，從而提高溝通效率，
工作輸出。

具體來說，和命令導向的人溝通，要注意：

1. 快速進入主題，說重點
2. 提供充足信息做參考
3. 充分表達不同意見
4. 主動發起溝通談話
5. 快速果斷做出決定

和詢問導向的人溝通，注意：
1. 徵詢對方意見
2. 放慢步調，充分討論
3. 注意傾聽，避免打斷對方
4. 預留足夠的停頓和安靜思考的時間
5. 避免施加太大的壓力

和任務導向的人溝通時：
1. 就事論事，討論工作事實
2. 解釋論斷後面的邏輯思路
3. 認可其時間效率上的顧慮
4. 減少誇張的手勢和面部表情
5. 避免閒談

和人際導向的人溝通時：
1. 表達自己的個人感情
2. 對個人的貢獻給予肯定
3. 願意在工作場合以外分享私人生活經歷
4. 增加身體語言，面部表情以及身體接觸
5. 增加聲調的變化，抑揚頓挫

說到調整溝通方式以迎合溝通對象這個話題，不得不提莊子《人間世》篇。《人間世》可以
說完全是有效溝通的案例分析論文。

《人間世》第一個故事借顏回打算去衛國匡正獨斷專行的衛王，和他的老師提出自己應對衛
王的策略：

#+BEGIN_QUOTE
我內直而外曲，成而上比。內直者，與天為徒。與天為徒者，知天子之與己皆天之所子，而
獨以己言蘄乎而人善之，蘄乎而人不善之邪？若然者，人謂之童子，是之謂與天為徒。外曲
者，與人之為徒也。擎、跽、曲拳，人臣之禮也，人皆為之，吾敢不為邪！為人之所為者，
人亦无疵焉，是之謂與人為徒。成而上比者，與古為徒。其言雖教，讁之實也。古之有也，
非吾有也。若然者，雖直不為病，是之謂與古為徒。
#+END_QUOTE

顏回提出了很重要的一個方法：“內直而外曲，成而上比”。“內直”就是直面人的本性，接受
人性的種種事實以及弱點，“外曲”就是所謂的迎合，人臣之禮人皆爲之，也不能少。“成而
上比”就是根據歷史經驗事實來發表論斷，這樣就不會遭受攻擊。儘管顏回這樣做已經非常
高妙了，但是後面孔子還是給予否定，並提出了更加高超的“氣聽心齋法”。暫且不論。

《人間世》後面還有一則故事，這次是顏闔要去做衛太子的老師。這個衛太子就是前面提到
的衛王，故事發生的時間線更早一些，那時候衛王還只是個太子。顏闔就去請教蘧伯玉，說：
“有人於此，其德天殺。與之為無方，則危吾國；與之為有方，則危吾身。”（老師啊，我要
去做這樣一種人的老師，他的品性簡直是 God damned，不好好教他，那我們國家就完了；
好好教他，恐怕他會恨我，我小命不保！）蘧伯玉就教他：

#+BEGIN_QUOTE
形莫若就，心莫若和。雖然，之二者有患。就不欲入，和不欲出。形就而入，且為顛為滅，
為崩為蹶。心和而出，且為聲為名，為妖為孽。彼且為嬰兒，亦與之為嬰兒；彼且為無町畦，
亦與之為無町畦；彼且為無崖，亦與之為無崖。達之，入於無疵。
#+END_QUOTE

這段也很好的描述了迎合方法，並且講了迎合中的注意事項：外在言語、行爲儘量的去迎合，
內在要保持自己的原則暗中疏導。但是要注意，不可以一味的迎合而失去內在的主張，也不
可內在主張太過顯露。對方像個嬰兒一樣喜怒無常天真直率，那就表現和他一樣做個性情中
人；對方如果和你沒有隔閡，那就表現和他一樣率性而爲；對方如果無拘無束，那就和他一
樣無拘無束。這樣就可以達到沒有過錯，就可以慢慢對其進行疏導了。

* 總結

本文首先介紹了社交風格類型和性格色彩學，並引用了孔子的觀人識人方法，然後介紹了分
析和調整的方法，並圍繞莊子《人間世》中的兩個運用迎合能力的案例進行了討論。

迎合的方法是先識別自己和對方的社交風格，再分析，最後調整自己的溝通方式。但這不是
溝通的結束，在後續的溝通中要繼續識別，再持續分析，不斷調整。

迎合能力是一種非常重要的人際交往技巧，不僅可以用在工作溝通中，也可以用在生活的方
方面面，好好學習運用必定可以提高工作和人生的效能。

* Footnotes

[fn:1] http://www.wilsonlearning.com/wlw/articles/w/hidden-cost-comm/en

[fn:2] 關於 versatile，請詳見上月的文章 July 9, 2016 » 单词本：英语单词versatile
http://kimi.im/2016-07-09-english-versatile

[fn:3] http://baike.baidu.com/view/3438641.htm
