@startmindmap
+ [latin] \n rigo \n rigare
++ regna
+++ [de] regnen (vi)
++++ Regen (n)
+++ [se] regna (vi)
++++ regn (n)
+++ rain
++ [latin]\nirrigare \nirragatus
+++ irrigate 灌溉
++++ irrigable 可灌溉的
++++ irrigator 灌溉者
++++ irrigative 灌溉的
@endmindmap
