#+BEGIN_HTML
---
layout: post
title: 单词本：德语单词 auskommen
categories: [language]
tags: [Deutsch]
---
#+END_HTML

前几天公众号订阅好友花花同学提议说希望多增加一些德语单词学习的文章，其实我的生词
本里也累计了不少德语单词的，但是本人德语学的太差，就任由长长的生词列表慢慢的增长
而没有采取什么积极的行动去消灭它们。有人提议要增加德语学习的比重，那对我来说是最
好的激励了，所以就努力去把手头的生词列表消灭掉吧。

很久很久以前，遇到了 auskommen 这个单词，我把它摘录到生词列表中。它就一直躺在那
里，渐渐发霉。直到今天，才拎出来钻研学习它。

* auskommen

首先，首字母大写的 Auskommen 是一个中性名词，意为生计（livelihood）或者说是收入、
工资。这和英语里的 income 差不多。只是有点奇怪的是 income 很容易理解是 in（入）+
come，而 Auskommen 则是 aus（出）+kommen。大概可以这样理解吧。前者是收入，而后者
是产出。有了产出才会有收入吧。当然了，后文中我们会知道，auskommen 是过活的意思，
也可以理解为可以用来养活自己的东西。
- Ich habe ein gutes Auskommen. 我收入还不错。

然后呢，auskommen 也是一个动词：合得来，适应的意思。
- Ich komme gut mit meine Frau aus. 我和太太相处的很融洽。
- Sie kommt ohne Sport nicht aus. 不运动她就难受。
- Wir kommen gut miteinander aus. Nous nous entendons bien l’un avec l’autre^fr.

* Derivation / 衍

** aus...kommen

可能需要注意的地方是，另外一个组合 aus...kommen和auskommen是不一样的。
aus...kommen经常用在自我介绍上，比如：
- Meine Frau kommt aus der Schweiz. 我太太来自瑞士。
- Das Mädchen kommt aus den Philippinen.

** auskömmlich

形容词：足够的，充裕的，合理的。adequate, sufficient, reasonable.

- Obwohl die Preise für Zementprodukte im Jahr 2005 im Durchschnitt um 10%
  erhöht werden konnten, sind diese immer noch nicht auskömmlich. 尽管水泥产品价
  格会涨 10%，却仍然不足。
- Trotz zunehmender Belastungen von der Währungsseite bleibt das
  weltwirtschaftliche Umfeld für die deutsche Wirtschaft auskömmlich. 尽管有流动
  性压力，世界经济环境对德国经济来说还是合理的。
- Allerdings sind die Preise immer noch nicht auskömmlich. However, the prices
  are still not adequate.

** Auskömmlichkeit

Die Auskömmlichkeit。名词：充裕性。

- Die Auskömmlichkeit wird durch regelmäßige aktuarielle Untersuchungen
  überprüft.
- Die Auskömmlichkeit von Angeboten ist nicht immer leicht zu ermittlen.[fn:1]供
  给的充裕性总是不太容易估算。

* Afterword / 跋

学习新单词的乐趣之一就不经意间又一次偶遇，比如昨天学习 arbitration 的时候用的例
句：Ich will, dass Sie einen Streit schlichten. 遇到了 Streit，今天学习auskommen
又遇到它 streitet：Kommt ihr gut miteinander aus oder streitet ihr häufig? 这样
对 Streit/streiten 就留下了很深的记忆了。

* Footnotes

[fn:1] www.abz-bayern.de/abz/inhalte/Aktuelles/thema-des-monats2/januar-2014-die-ermittlung-der-auskoemmlichkeit-von-angeboten.html
