#+BEGIN_HTML
---
layout: post
title: 單詞本：搶座
categories: [language]
tags: [English]
---
#+END_HTML

昨晚花了三個小時從杭州來到了上海。虹橋火車站下車之後坐 2 號線地鐵。各個車門前早
已排起了長隊，提着行李的，拎着包的，揹着包的，還有抱着棉被枕頭的；滿頭大汗的，汗
流浹背的，神色慌張的，急急忙忙的，鬼鬼祟祟的，東張西望的。

等到地鐵呼嘯着進站，人們齊刷刷地地望向地鐵車廂，抓緊行李，雙手拎包，抱緊棉被，等
着門開的一刻，泄洪般涌進車廂，說時遲那時快，不到兩秒鍾時間，地鐵內的座位已經被填
滿。然後剩餘的地方也陸陸續續的被站滿。

沒有搶到座的人們只能無奈的笑笑，抓緊了把手，等待地鐵發動。我也是那無奈的一個。這
就是上海虹橋地鐵首發站站驚心動魄的一刻。

地鐵搶座（grab the seat）也是很有趣的一道風景。座位資源有限，拼的就是速度。大家
都講規則，等車時按前後順序車門兩側排好隊伍。腿快有，腿慢無，實在是很公平的競爭。
搶到座的，掏出手機看看小說，讀讀新聞，聊聊微信，不亦樂乎；搶不到座的，調整好站姿，
也能掏出手機，沉浸在信息知識的海洋裏，忘卻剛才汲汲營營的追逐。

比如那位抱着棉被枕頭的小姑娘，如果不搶個好的座兒，豈不是要擁着枕頭、棉被、行李箱
站着，那實在是太辛苦了。其實她已經錯過一班車了，這次是她等的第二班車。估計前一班
車她沒有搶到座，所以不辭辛勞，再等一班，這次她排在隊伍前面，所以找到了一個心儀的
座位。有了穩妥的座位，她就可以愉快的和夥伴語音聊微信了。

而旁邊這位姑娘就不怎麼幸運，被擠在了人羣中間，看似她業務很忙，左手一個 iPhone 6
plus，右手一個華爲榮耀，兩隻手同時開工，突然地鐵一陣剎車，她被甩到了一位手臂紋着
骷髏紋身，正在坐在座位上用手機閱讀小說的男子懷中。他不曾想到佔個座位還能有美女投
懷送抱的福利。

搶座這個動作，在英語裏是 grab the/a seat：

- Overall, it is safe to travel in Shanghai. But you should take good care of
  your belongings if you are in a highly crowded place as there might be
  cutpurses. Theft is highly likely to occur while people rush for arriving bus
  or sub ways, hoping to /grab a seat/.[fn:1]
- It’s happened to Hannah Horvath on Girls, and maybe it’s even happened to
  you. You /grab a seat/ on the New York subway, let your eyes flutter shut, and
  when you open them again, you’re in Coney Island.[fn:2]

* Grab

越是簡單的單詞，越是含義豐富。似乎到哪裏都一樣。學習這種單詞還是挺繁瑣的，因爲含
義豐富，要好好掌握難度很大。

#+BEGIN_QUOTE
1. to seize suddenly, eagerly, or roughly; snatch. 突然抓取
2. to take illegal possession of; seize forcibly or unscrupulously 霸佔，搶奪:
   to grab land. 霸佔土地。
3. a sudden, eager grasp or snatch. 猛抓的動作。
4. seizure or acquisition by violent or unscrupulous means. 搶奪的動作。
5. something that is grabbed. 被抓住的東西。
6. a mechanical device for gripping objects. 抓取設備。
7. to obtain and consume quickly 猛吃: Let's grab a sandwich. 讓我們快速解決這個
   三明治。
8. to cause a reaction in; affect 引入注意: How does my idea grab you? 你對我的
   想法感興趣不？
#+END_QUOTE

** 突然抓取

- He grabbed the pen from me.
- The woman with him to grab a seat, he did not.
- A man then got out and grabbed a white turkey and drove off southbound on
  S.R. 3. [fn:3] 昨天的新聞，美國的有人在馬路上抓了只火雞就跑了。

** 霸佔，搶奪

- Fans line up outside store to /grab/ Harry Potter book
- Anurag Pathak, a 27-year-old Harry Potter fan, cancelled his office trip to
  Nainital to be able to /grab/ the book. She had reached the Hazratganj shop at
  10am, two hours before the sale of 'Harry Potter and the Cursed Child' had to
  begin.
- Not only children, but adults too, made sure to steer clear of other plans on
  the weekend and visit the bookstore to /grab/ their copy.[fn:5] 不止小朋友，大
  人們也跑去書店搶買哈利波特新書《哈利波波特和被詛咒的孩子》。
- Turkey, US meet after power grab attempt.[fn:6] 前一篇文章《單詞本：德語單詞
  Putsch》提到過政變可以稱 Putsch attempt，也可以叫 coup d'état，這則新聞有出來
  個說法：power grab attempt。能把所學的知識連貫起來是一件很好玩的事情。不是嗎？

** 猛抓的動作

- Fan reaches way over the rail for sweet grab[fn:7]

** 猛吃，快速吃掉

- Let me just grab some French bread for dinner and we can check out. 我去弄些法
  國麪包當晚餐，然後我們就離開。
- I think I'll just run downstairs and grab a cup of coffee.

** 引人注意

- How does that grab you? 你對此感興趣不？
- How does my idea grab you?

** grab-and-go

拿了就走的快餐，食物：

- Raw vegetables and fruits are great grab-and-go snacks. 蔬菜和水果是很好的拿着
  就吃的點心。
- Lately I have been making a raw kale salad, which not only uses up some of the
  greens I get, but also makes a great grab-and-go lunch.[fn:8]

* Footnotes

[fn:1] http://wiki.magicjudges.org/pool/images/c/c7/Travelguide_GP_Shanghai_2012.pdf

[fn:2] http://newsfeed.time.com/2013/09/18/napping-on-the-subway-this-app-will-wake-you-up-before-you-miss-your-stop/

[fn:3] http://wane.com/2016/08/01/turkey-stolen-in-roadside-grab-and-go/

[fn:4] http://www.answers.com/Q/Grab_women_breast

[fn:5] http://www.nyoooz.com/lucknow/558663/fans-line-up-outside-store-to-grab-harry-potter-book

[fn:6] http://www.france24.com/en/20160801-turkey-us-meet-after-power-grab-attempt

[fn:7] http://espn.go.com/mlb/story/_/page/tradedeadline_upsidedowndeadline/how-cubs-indians-yankees-turned-deadline-upside-down

[fn:8] http://www.pressrepublican.com/opinion/columns/with-salads-try-more-than-just-classics/article_c69b68ea-d3b6-547e-9b00-f55b6558cf48.html
