#+BEGIN_HTML
---
layout: post
title: 单词本：食物
categories: [language]
tags: [English]
---
#+END_HTML

上周出差去上海，回来发现公司领导组织了一次常见食物英语单词学习的活动。既然错过了，
就好好自学一下吧。

常见食物可以分成这样几类：
1. Cereal grain：谷物
2. Vegetables：蔬菜
3. Fruits：水果
4. Animal source food：动物性食物
5. Bean：豆类，豆制品
6. Edible fungi, especially mushrooms：食用菌，蘑菇
7. Drinks：饮料

* Cereal grain

Cereal grain is a staple food. 谷物类食物中最常见的就是米饭了，另外还有比如小米，
大麦，黑米，玉米。

** rice

大米，水稻的种子。

As a cereal grain, *rice* is the most widely consumed staple food for a large
part of the world's human population, especially in Asia.[fn:1]

法语 *Le riz^fr* est une céréale de la famille des poacées.[fn:2]

德语 *Der Reis^de*

米饭就是煮熟的大米，所以就叫 cooked rice 或者 boiled rice。顺便提一下，水稻学名
叫 Oryza sativa，稻田叫 paddy。

** wheat

小麦，学名 Triticum。德语 der Weizen^de，法语 le blé^fr.

Le blé fait partie des trois grandes céréales avec le maïs et le riz.[fn:3] 小麦
和玉米，大米号称三大谷物。

小麦是以下这些食物的原料：

- bread：面包，le pain^fr, das Brot^de.
- porridge：麦片粥，La bouillie^fr, der Brei^de.
- biscuit：饼干，le biscuit^fr, das Keks^de.
- Muesli：木斯里，流行德国瑞士的一种麦片+水果+坚果的牛奶泡着吃的食物。之前我们公
  司一个德国同事经常早上泡着吃。Müsli^de.
- muffin：玛芬蛋糕，松饼。德语，法语英语拼写都一样。
- rolls：小圆面包，das Brötchen^de, le petit pain^fr
- doughnuts：甜甜圈，le donut^fr, der Donut^de.
- boza (a fermented beverage)：小麦发酵饮料。好像之前在一家墨西哥餐厅喝到过。

** millet

小米，粟米。德语叫 die Hirse^de, 法语叫 le millet^fr. 说起小米，有一回和德国人去
餐厅吃小米糕，怎么也没法沟通到底是什么东西做的。最后大概是互相理解了，也只能呵呵
当做理解了。现在想起来，可能当时他们在说这东西在我们那儿叫 Hirse。不过谁知道呢？
今天学习到了，下次倒是可以很好的解释了。

既然小米是 millet，那么小米糕就是 millet cake 了。

** black rice

黑米，也叫紫米，长寿米。相应的，英语叫 black rice，purple rice，又叫 longevity
rice。称它为长寿米是因为古代医书有记载：黑米有滋阴补肾，健身暖胃，明目活血，清肝
润肠，滑湿益精，补肺缓筋等功效。这么看来，早上喝喝黑米粥还是健康的事情了。

法语 le riz noir^fr, 黑的米。德语自然就叫 der schwerz Reis^de.

** corn(maize)

玉米，corn 又叫 maize。英语里 corn 可能指各种类型的谷物，因为玉米的学名是 Zea
mays L. 所以用 maize 来称呼玉米可能更精确一些。

法语 le maïs^fr. 以前学法语的时候，mais 和 maïs 经常被拿出来用于说明两个小圆点分
音符的作用，还有一个例子就是 naïve。

德语叫 der Mais^de，没什么悬念。西方世界对玉米的称呼比较统一。

* 小结

本来计划是要把食物相关的主要单词都学习一下的，但是写着写着发现仅仅谷物部分就已经
有不少篇幅了。所以就把其他几种食物放到后续的文章中去学习吧。

* Footnotes

[fn:1] https://en.wikipedia.org/wiki/Rice

[fn:2] https://fr.wikipedia.org/wiki/Riz

[fn:3] https://fr.wikipedia.org/wiki/Bl%C3%A9
