#+BEGIN_HTML
---
layout: post
title: 单词本：德语单词 Putsch
categories: [language]
tags: [Deutsch]
---
#+END_HTML

虽然标题是德语单词 Putsch，但其实主要还是学习英语单词 putsch 和 coup。

自从上周五晚上土耳其发生武装政变（Militärputsch）以来，就滔滔不绝的关于土耳其政
变的新闻。其实我最早看到这次政变的新闻标题是用的 coup d'état 这个单词。总之
putsch 和 coup d'état 都出现在英语新闻中，比如：

#+BEGIN_QUOTE
A coup d'état attempt took place in Turkey on 15 July 2016. It is believed it
was done by part of the Turkish Armed Forces.
#+END_QUOTE

又比如：

#+BEGIN_QUOTE
Turkey's Putsch and the Democratic Dilemma.
#+END_QUOTE

所以我一开始也选不好标题，到底是该定这篇文章的主题为 putsch 呢，还是 coup d'état？
无论如何，这两个词对我来说都是新单词，所以就一起来学一学好了。

* Putsch

很明显，Putsch 对英语来说是个外来词。尽管在英语词典里有 putsch 这个词，但是追根
溯源，还是来自德语：

#+BEGIN_QUOTE
A sudden attempt by a group to overthrow a government. From German Putsch.
#+END_QUOTE

其实有一个小技巧可以很容易区分是不是德语单词，就像 Deutsch 一样，有 -tsch 结尾的
单词，一般来说都来自德国（Deutschland）。

那么在德语里，Der Putsch 有两个意思：

#+BEGIN_QUOTE
1. Von einer kleineren Gruppe [von Militärs] durchgeführter Umsturz[versuch] zur
   Übernahme der Staatsgewalt
2. Stoß
#+END_QUOTE

第一，一小撮军方发起的夺权行动，即政变。第二，重击。我们后面会知道，coup 在法语
里也是重击的意思。所以，英语里博采众长，coup 和 putsch 都采纳进来了。

* Coup d'état

再一次很明显，这个词组来自法语，带小帽子的 é 出卖了它。

让我们回过头来先看看在英语词典里 coup 是什么意思：

surprising and successful action. 意外并且成功的行动。比如 She pulled off a
great coup in getting the president to agree to an interview. 她成功办到让总统接
受她的采访。注意，因为 coup 是从法语里面借来的，所以保留了法语发音，结尾p 是不发
音的，coup 读作 [kuː]，great [kuː]，伟大的酷。重要的事情说三遍。

言归正传，coup d'état 就是所谓的政变，复数形式的 -s 要加在 coup 后面，写作 coup
d'état。发音也仿照法语读作 [kuː dei 'ta] 或者快一些 [ku de 'ta]。顺便提一下，英
语中还引入了 coup 的另一个词组 coup de grâce，这个词指的是”出于好意使其免遭痛苦
的致命一击“，比如 Poor exam results dealt the coup de grâce to his hopes of
becoming a PhD. 对了，还是要注意 coup de grâce 得用法语发音：[ku də ɡrɑː]。

好了，现在我们转入法语部分，coup 这个词在法语里是 blow^en 重击的意思： Il a pris
un coup sur la tête. 他敲了他的头。Il m'a donné un coup. 他撞了我一下。

coup 组成的词组还是挺有意思的比如：

- à coup sûr 必须的，肯定的，definitely
- dans le coup, être dans le coup: know all about it. mettre qn dans le coup: to
  get sb involved. 把某人牵扯进来。
- du coup: as a result
- du premier coup: 一击必胜。Il a eu son permis de conduire du premier coup. 他
  一把就通过了驾驶考试。
- tout à coup, tout d'un coup: all of a sudden
- valoir le coup: 值得一试。ça vaut le coup. It's worth it. c'est un film qui
  vaut le coup. 那电影值得一看。

* Example / 例

- The Turkish army has historically intervened in politics as it sees itself as
  the protector of Turkey's secularism and democracy - there have been four
  military /coups/ since 1960. 英语里 coup d'état 也可以简写为 coup，military
  coup。
- Soon after, Prime Minister Binali Yildirim announced that an attempt to
  overthrow the government was under way. 英语里直白的话就用 an attempt to
  overthrow the goverment，稍微繁琐一些，但很明白易懂。
- Purge générale en Turquie après le putsch manqué de la nuit du vendredi 15 au
  samedi 16 juillet. 法语里也有用 le putsch 表示政变的。
- Le Premier ministre a d'autre part annoncé la mort de de 308 personnes dans la
  tentative de coup d'État : 60 policiers, trois soldats et 145 civils. 法语里
  coup d'État 中 état 的首字母是大写的。
- Mehr als 250 Menschen sind tot, mehr als 1000 wurden beim Putschversuch in der
  Türkei verletzt - Präsident Recep Tayyip Erdoğan antwortet mit
  Härte.
- Nun ist Akın Öztürk in Haft. Er soll beim Putschversuch eine zentrale Rolle
  gespielt haben. Putschversuch 政变企图，coup attempt。
- Akın Öztürk dementierte, ein /Putschist/ zu sein. Akın 否认自己是一个政变者。
  Putschist 政变者，insurgent^en。
- After a night which saw /putschist/ troops fire into crowds of loyalist
  civilians, the government announces it has foiled the attempt and regained
  complete control of the country.[fn:1] 英语里也有。
- Der versuchte Staatsstreich begann demnach auf der Militärbasis Akıncı bei
  Ankara, die der Schwiegersohn von Öztürk kontrollierte. 德语里也有直白一点的说
  法 der versuchte Staatsstreich，政变企图。

* Footnotes

[fn:1] http://www.dailymail.co.uk/news/article-3693332/Trapped-fire-collapse-terrorism-recession-left-popular-Turkish-president-battling-fronts-decade-unprecedented-growth.html
