#+BEGIN_HTML
---
layout: post
title: 单词本：蔬菜
categories: [language]
tags: [English]
---
#+END_HTML

上一篇小文章提到学习食物相关的一些单词，文章开头列了几种食物分类，全文只是介绍了
谷物类食物的单词，今天继续学习一下蔬菜相关的单词。

* Vegetable

vegetable 是蔬菜的统称，法语 le légume^fr 德语 der Gemüse^de。

只吃蔬菜的人素食者就是 vegetarian，vegan 和 veggie 大概是昵称吧。我记得王菲的微
博名就叫 Veggieg[fn:1]，大概是王菲是素食主义者吧。

法语 végétarien(ne)，德语 Veganer(in)，Vegetarier(in)。

素食主义 veganism 又叫 vegetarianism，le veganisme^fr, le végétalisme^fr, der
Veganismus^de. 顺便提一下： carnivorism 肉食主义，carnivorse 食肉动物。

veggieburger, Gemüseburger^de，素汉堡。

蔬菜的种类实在太多了，比如萝卜、胡萝卜、白菜、甘蓝、花菜、芹菜、茄子、番茄、辣椒、
黄瓜、西葫芦、南瓜、冬瓜、丝瓜、苦瓜、豇豆、豌豆、蚕豆、毛豆、扁豆、刀豆、韭菜、
洋葱、大蒜、黄花菜、芦笋、竹笋、百合、莴苣、莴笋、茼蒿、菠菜……

看来今天也只能先选两三个学习一下了，就先看看萝卜和胡萝卜这两个很容易混在一起的蔬
菜吧。其实，萝卜和胡萝卜在英语中完全是两类毫不相干的蔬菜，大概都是根茎蔬菜，又长
的比较像，所以咱们统称他们为萝卜吧。

* radish

萝卜：radish^en，der Rettich^de, le radis。英法德在萝卜的命名上保持了很好的一致
性。往往能保持很好的一致性的单词，其背后都有古老的拉丁语支持着。

果然 radish 源自拉丁语 radix，radic，“root”的意思。也就是说 radix有“根”“根基”“根
本”之意。

比如 radical 根本的，彻底的，free redicals 自由基，radical sign 开根号：
√,radicle 胚根。萝卜这个单词扩展开还是蛮多知识点可以讨论的，暂且不展开了吧，下次
有空了另写一篇吧。

dried radish slices 萝卜干

* carrot

胡萝卜，la carrote^fr, die Karotte^de, die Möhre^de。胡萝卜含有特殊的成分叫胡萝
卜素 carotene，le carotène^fr。这里要注意一下，ca 和 o 之间只有一个 r，英语和法
语的拼写一样。

另外还有几个胡萝卜相关的成语：
- the carrot and the stick 胡萝卜加大棒，威逼利诱；manier la carotte et le
  bâton^fr，法语版胡萝卜+大棒；mit Zuckerbrot und Peitsche
  德语版甜面包+皮鞭；
- hold out/offer a carrot to sb. 利诱某人；德语版 jmdm. einen Köder vor die Nase
  halten 在某人鼻子前挂个诱饵。carotter qch à qn^fr，法语直接将胡萝卜动词化：从
  某人那里胡萝卜了某物，换句话说，从某人哪里骗取了某物。Elle m'a carotté dix
  euros^fr 她从我这里骗走了 10 欧元。Je me suis encore fait carrotter^fr 我又被
  骗了一次。

胡萝卜做的菜：
- grated carrots，carottes râpées^fr，geraspelte Möhren od. Karotten^de，擦碎的胡萝卜。
- boiled beef and carrots 胡萝卜清炖牛肉

* 小结

今天本打算学习几个主要的蔬菜相关的单词，但是写着写着发现仅仅萝卜和胡萝卜就占据了
很大的篇幅，看来今后一篇文章只能学习两种蔬菜了。不着急，慢慢来，太快了，就享受不
了学习的乐趣了，再说了，反正人生还很漫长，急什么。

* Footnotes

[fn:1] http://weibo.com/u/1629810574
