#+BEGIN_HTML
---
layout: post
title: 单词本：蔬菜之韭菜
categories: [language]
tags: [English]
---
#+END_HTML

* chives

本来打算学习韭菜的，后来发现韭菜原来叫 Chinese chives 中国细香葱。而 chives 则是
细香葱的意思。百度百科说：

#+BEGIN_QUOTE
虾夷葱 (Allium schoenoprasum)，又称小葱、细香葱、香葱，或直接简称为葱。[fn:1]
#+END_QUOTE

虾夷葱我还是头一次听说，好奇怪的名字啊。说起虾夷，我记得之前我在一本关于日本的书
中了解到，北海道地区的原住民就叫虾夷人[fn:2]，体型比较矮小，但很凶悍。经常骚扰日
本天皇的领地，但最终被天皇给灭了。或许是因为这种葱来自北海道，又或许是葱的体型细
细的如虾夷人？不得而知了。顺便提一下，北海道古称虾夷，日语写法为：えみし
（emishi）。也许下一次你去北海道玩，和北海道的日本人说 えみし，他们定会惊讶于你
的人文地理历史知识渊博。

德语管虾夷葱叫 der Schnittlauch^(de)，schnitt 切割，der Lauch[laux]^(de) 葱。小
切葱？

法语叫 la ciboulette[sibulɛt]^(fr)，而 la ciboule[sibul]^(fr) 则是葱的名号。La
ciboulette est une plante aromatique^(fr). 小香葱是一种香料植物。

* Chinese chives

韭菜好像是中国特有，所以被叫做中国细香葱。另外还有其他好多名字：garlic chives 大
蒜葱, oriental garlic 东方大蒜, Asian chives 亚洲小香葱, Chinese chives 中国小香
葱, Chinese leek 中国大葱[fn:3]。

法语叫 la ciboule(tte) chinoise^(fr)，和英语一样，也认为韭菜是中国特有的小葱。

德语叫 der Knoblauch-Schnittlauch^(fr)，就有点怪怪的了：葱蒜切葱[fn:4]吗？

* leek

前面出现过的，韭菜又叫 Chinese leek，而 leek 则是大葱的名字。知道了 leek 再回过
头看看小葱的的名字 der Schnittlauch 就不太陌生了。Lauch 和 leek 不就是一对双胞胎
么。

大葱的法语名字却叫 le poireau[pwaʀo]^(fr)，另外还有法语名字如 l(a)'asperge du
pauvre^(fr)，l'asperge^(fr) 芦笋，pauvre^(fr) 穷人。正如后面会提到的，在英语里
not worth a leek 形容毫无价值，在法语里穷人的芦笋就是大葱。可见英国法国人的心目
中大葱多么低廉啊。

** not worth a leek

大葱可能比较容易种植，所以比较廉价，就有毫无价值之意了：
- What he said is not worth a leek. 他说的东西不值一葱。只值一葱已经很低贱了，不
  值一葱那简直太伤人了。

** to eat the leek

另外大葱的味道不是人人都喜欢，所以 to eat the leek 有忍辱负重之意：
- James felt bad when he was obliged to eat the leek. 詹姆士被迫忍受屈辱感觉很难受。
- She had to eat the leek then. 那时候她只能忍受屈辱。

* Summary

本文本来计划学习韭菜的名字，后来发现韭菜其实在英国法国被称作中国小香葱（Chinese
chives，la ciboulette chinoise^(fr) ），在德国被称作葱蒜切葱（der
Knoblauch-Schnittlauch^(de)）。于是又学习了小香葱（chives，la ciboulette^(fr)，
der Schnittlauch^(de) ）和大葱（leek，le poireau^(fr)，der Lauch^(de) ）两组单词。

另外还学会了英语里两个成语不值一葱（not worth a leek）和忍辱吃葱（to eat the
leek）。下次吃葱的时候可以羞辱讨厌的人说：You are not worth a leek, I must let
you to eat the leek!  （你不值一文，我必定让你忍受屈辱！）

不过话说回来，我还是希望诸位这一生不要遇到这样的混蛋，希望你们能遇到的都是和小香
葱一样可爱的人。

* Footnotes

[fn:1] http://baike.baidu.com/view/92921.htm

[fn:2] http://baike.baidu.com/view/76793.htm

[fn:3] https://en.wikipedia.org/wiki/Allium_tuberosum

[fn:4] https://de.wikipedia.org/wiki/Knoblauch-Schnittlauch
