#+BEGIN_HTML
---
layout: post
title: 单词本：水果之香蕉
categories: [language]
tags: [English, Deutsch, Français]
---
#+END_HTML

* banana

香蕉 banana。

在我读大学的时候，香蕉还是很便宜的，学校水果店里一元钱好几个香蕉可以买。最喜欢吃
黄色的水果，像芒果啊，香蕉啊，橘子啊，菠萝啊之类的水果，都是我的最爱。所以，大学
时候常常每天买很多黄色的水果吃。好怀念啊。

为了更好的阅读本文，请响起背景音乐：http://www.kuwo.cn/yinyue/5429060/

#+BEGIN_VERSE
来来 我是一个菠菜
菜菜菜菜菜菜菜菜菜菜菜菜菜菜菜菜
来来 我是一片芒果
果果果果果果果果果果果果果果果
来来 我是一个竹笋
笋笋笋笋笋笋笋笋笋笋笋笋笋笋笋笋
来来 我是一快菠萝
萝萝萝萝萝萝萝萝萝萝萝萝萝萝萝
来来 我是一粒草莓
莓莓莓莓莓莓莓莓莓莓莓莓莓莓莓莓
来来 我是一只香蕉
蕉蕉蕉蕉蕉蕉蕉蕉蕉蕉蕉蕉蕉蕉蕉
来来 我是一个葡萄
萄萄萄萄萄萄萄萄萄萄萄萄萄萄萄萄
来来 我是一个蜜糖
糖糖糖糖糖糖糖糖糖糖糖糖糖糖糖[fn:1]
#+END_VERSE

** banana color

香蕉黄。

有的认为 banana color RGB 颜色编号为#FFE135[fn:2]：
#+BEGIN_HTML
<h3 style="background-color: #FFE135; width: 80px;">&nbsp;</h3>
#+END_HTML

也有的认为是 #E3CF57[fn:3]
#+BEGIN_HTML
<h3 style="background-color: #E3CF57; width: 80px;">&nbsp;</h3>
#+END_HTML

我比较觉得应该是第二种颜色。你觉得呢？

另外还有个绿香蕉（Green Banana）色，RGB #B7BD6B[fn:4]
#+BEGIN_HTML
<h3 style="background-color: #B7BD6B; width: 80px;">&nbsp;</h3>
#+END_HTML

** 香蕉人

上次的文章[[http://kimi.im/2016-10-03-english-apple][October 3, 2016 » 单词本：水果之苹果]]中提到苹果人的时候也扯到香蕉人的说
法：

#+BEGIN_QUOTE
A person of Asian descent, especially a Chinese American, who has assimilated
into Western culture or married a Caucasian (from the "yellow" outside and
"white" inside). Compare coconut ‎(“assimilated Hispanic or Black”) or Oreo
‎(“Black person who is "black outside" and "white inside"”).[fn:5]
#+END_QUOTE

所谓的香蕉人指的是美国亚裔，当然亚裔中最多的还是华人，用香蕉形象的比喻 yellow
outside and white inside。椰子和奥利奥则形容 black outside white inside。

看来人们比较喜欢用色彩斑斓的水果形容人种文化差异。

* die Banane^{(de)}, la banane^{(fr)}

香蕉在法语和德语比较一致，都是阴性，拼写也都一样。

法语口语里用香蕉形容别人幼稚愚蠢 personne ayant une pensée naïve ou idiote：
- Tu veux ma photo, banane？ 笨香蕉，你看过我的照片？

* le bananier^{(fr)}

香蕉树

* je suis une banana^{(fr)}

我找到一首法语神曲，和古天乐《我是一个芒果》真是异曲同工：

#+BEGIN_VERSE
Je suis une banane,
Je suis une banane,
Je suis une banane,
Regarde-moi bouger

Ouais, ouais![fn:6]
#+END_VERSE

* 香蕉的食疗价值

根据百度百科的建议，秋季似乎是比较适合吃香蕉的季节。天干物燥的，心情烦闷，最适合
吃香蕉了：

#+BEGIN_QUOTE
根据“热者寒之”的原理，最适合燥热人士享用。痔疮出血者、因燥热而致胎动不安者，都可
生吃蕉肉。

德国研究人员表示，用香蕉可治抑郁和情绪不安，因它能促进大脑分泌内啡化学物质。它能
缓和紧张的情绪，提高工作效率，降低疲劳。[fn:7]
#+END_QUOTE

最近睡眠不太好，心情有些烦躁，看来该多吃点香蕉！


* Footnotes

[fn:1] http://pu.onegreen.net/GeCi/HTML/22079.html

[fn:2] http://colors.findthedata.com/l/557/Banana-Yellow

[fn:3] https://rgbcolorcode.com/color/banana

[fn:4] https://www.pantone.com/color-finder/14-0434-TPX

[fn:5] https://en.wiktionary.org/wiki/banana

[fn:6] http://lyricstranslate.com/en/im-banana-je-suis-une-banane.html

[fn:7] http://baike.baidu.com/subview/3907/14798168.htm
