#+BEGIN_EXPORT html
---
layout: post
title: 单词本：亡命之徒
categories: [language]
tags: [English]
---
#+END_EXPORT

* 巴西囚犯越狱在逃

事情是这样的，前天，也就是 2017 年的元旦，巴西 Amasonas 州 Manaus 市 Antonio
Trindade 监狱发生暴乱，死伤惨重，50 名囚犯遇难，87 名囚犯在逃。其中一名叫做
Brayan Bremer 的在逃囚犯居然还抽空摆了个漂亮的 pose 拍了张自拍照上传到脸书。一时
间引起网络一片哗然，人们纷纷用 Brayan 的头像制作影视剧海报，比如《Um Sonho de
Liberdade》，《Prison Break》。

在 BBC 的一则新闻里《[[http://www.bbc.com/news/world-latin-america-38495374][Brazil prison escape: Fugitive posts selfies on the run]]》
 [fn:1]，我们可以学习到逃犯的英语单词：fugitive[ˈfju:dʒətɪv]和
 escapee[ɪˌskeɪˈpi:]。

今天首先学习那个复杂一点的单词 fugitive 吧。

* fugitive

从根源上来说，fugitive 源自拉丁语 fugio^{(latin)}，例如：Tempus fugit.^{(latin)}
时间过得飞快。

基于这样的词源，fugitive 就有两重意思。首先，它表示逃亡、消逝，其次，它有转瞬即逝
之意。

** 逃犯、逃亡者

作为名词，fugitive 有普通的逃亡者之意，也专门指从逃脱法网的逃犯（fugitive from
justice）之意。

- police in Manaus continued their search for the fugitives.[fn:1] Manaus 的警察
  继续巡捕这些逃犯。
- The rebel leader was a fugitive from justice. 叛乱头目是一名逃犯。在法律上，
  fugitive from justice 特指逃脱法律的逃犯。
- A solitary fugitive, he crossed the Turkish frontier.

** 流浪者

不过，有时候逃亡的目的是远离世俗的话，就不是逃犯了，是主动流浪的隐逸者。

- We also chanced upon fugitive monks. 我们有时候会偶遇流浪的僧侣，

** 短暂的，转瞬即逝的

容易逃逸的，容易消逝的，就是短暂的，转瞬即逝的。

- fugitive beauty 转瞬即逝的美，或者说是韶华易逝，也许更简洁点可以翻译成浮华吧。

** 难以捉摸的

因为转瞬即逝，所以难以捉摸，难以理解。就好比是女孩子的想法，总是转瞬即逝，因此难
以捉摸难以理解。

- fugitive solutions to the problem. 乍看起来好像是说逃犯的方案，不太合法的样子。
  其实是指难以捉摸的答案，或者说是费解的答案。其实我觉得可以翻译成逸解，逸：逃逸；
  解：答案。

* Summary

读新闻的时候看到 fugitive 这个单词，简单的挖掘了一下，发现它不仅是逃犯的意思，还有
逃亡，流浪，短暂，难以捉摸之意。

2017 年一开始就发生这种惨烈的越狱时间，注定了这是一个不同寻常的一年。这一年，特朗
普将上任做美国总统，这一年，法国和德国将开始总统大选。不知道欧美国家还会发生什么
样的大闹剧。

然而 2017 年，伟大的祖国将迎来中国人民解放军建军 90 周年，香港回归 20 周年，“一
带一路”国际合作高峰论坛，首艘货运飞船“天舟一号”升空，“嫦娥五号”登月。祝愿祖国繁
荣昌盛，早日完胜欧美。

* Footnotes

[fn:1] http://www.bbc.com/news/world-latin-america-38495374
