#+BEGIN_EXPORT html
---
layout: post
title: 单词本：无人机
categories: [language]
tags: [English]
---
#+END_EXPORT

近年来，无人机已经变得家喻户晓了。上周在上塘河边散步晒太阳，看到一位老者在河面上
放飞着一架海飞丝沐浴露大小的无人机。从心态来看，他比我年轻十几岁啊！老人家说他过
几天要和老伴要去内蒙古大草原玩，所以花了 6 千多买了个市面上最轻巧的无人机去航拍。
真是令人羡慕啊。我们这个时代五六十岁的老年人是最幸福的一群人了，他们已经退休，儿
女也已成家，手里领着养老金，自由自在，跳跳广场舞，玩玩无人机。而 30 岁上下年纪的
则是最辛苦的一群人了，他们上有老下有小，每天要勤勤恳恳工作。

不过，转念一想，其实我也不太有时间玩无人机，一般来说买来后基本上会放在家里积灰，
而且还占空间。于是，我又心情愉悦的享受午后的阳光去了。

* drone^{(en)}

刚才提到的无人机，通常都是用 drone[drəʊn]这个单词。专业一点叫 unmanned aerial
vehicle（UAV）无人飞行器，有时候也叫 unmanned aircraft system（UAS）无人飞机系统。

之所以叫 drone 是因为无人机在空中飞的时候像雄蜂一样发出嗡嗡声，而 drone 的本意就
是嗡嗡叫、雄蜂：
- A drone is a male bee. Drone 是雄蜂。
- A few are dimwitted drones, but most are talented, frustrated, wasted
  people. 有几个是愚笨的寄生虫，但是大多数是有才能却不得志而自暴自弃的人。（蜂巢
  里的雄峰通常比工蜂大，唯一的职责就是繁殖后代，一生只和母蜂王抱抱一次，完了就死
  掉了。所以不明就里的人以为它们是好吃懒做的寄生虫，其实真是错怪它们了，它们真的
  好伟大，牺牲了自己，繁衍了蜜蜂种群啊。）根据人们的误解，drone 也就有好吃懒做的
  寄生虫之意了。
- Ivy's voice droned, maddening as an insect around Kimi's head... 艾薇一直在吉
  米耳边嗡嗡地说个不停，他都快疯了。（这里 drone 用作动词：喋喋不休唠叨）

* le drone^{(fr)}

法语则是直接从英语中借来 un drone 这个单词。
- L'exposition des drones a attiré l'attention de nombreux visiteurs. 中国的彩虹
  无人机系统吸引了众多观众的目光。[fn:1]

* die Drohne^{(de)}

德语中的无人机貌似也是从英语借来的 eine Drohne：
- Unbemannte Luftfahrzeuge werden als Drohnen bezeichnet. 无人机也称作 Drohne。

另外，德语 ein Drohn[fn:2] 一只雄峰。

* Summary

英语里，drone 是飞行的时候嗡嗡响的雄峰，而雄峰看起来吃吃喝喝不干活所以也用来骂那
些好吃懒做的人，嗡嗡响形容人就是喋喋不休的说个不停，嗡嗡叫也引申为工作时候嗡嗡响
的无人机。

法语，德语也分别用 le drone 和 die Drohne 表示无人机。德语里 ein Drohn 也是雄峰之意。

最后，我想问，哪为小读者家里有无人机，借我玩玩呗！

* Footnotes

[fn:1] http://french.china.org.cn/china/txt/2012-11/15/content_27124114.htm

[fn:2] https://de.wikipedia.org/wiki/Drohn
