#+BEGIN_EXPORT html
---
layout: post
title: 单词本：paranoid
categories: [language]
tags: [English]
---
#+END_EXPORT

前几天读硬件安全模块文档（英文的）的时候，看到这句话：Depending on how
the secure hash is used, either can be correct; but because
cryptographers tend to be P3 people (Paid Professional Paranoids), the
latter is generally used for the strength of a well-designed secure
hash algorithm.[fn:1]

这里说密码学家通常都是P3人员，即：有偿职业偏执狂。挺有趣的称谓呀。

对我来说，这里有一个生词：paranoid [ˈpærənɔɪd] 多疑的，妄想的；患偏执
症的，患妄想症的；偏执狂，妄想症患者。

似乎 =-oid= 结尾的词，大多是细菌、生物、疾病相关，如：
- schizoid 精神分裂的
- phylloid 叶状茎
- virusoid 拟病毒；核壳内尖病毒
  
也有数理化术语，如 centroid 质心。

与 paranoid 相关的单词有两个，一个是 paranoia 即妄想症、偏执症，焦虑、
恐惧导致的迫害妄想（persecutory belief）。另一个是 paranoiac 与
paranoid 意思相同，不过我感觉前者更偏名词，后者更偏形容词。

例句：
- the violent defensiveness of the paranoiac is directed against all
  who challenge his power. 偏执狂对质疑他权力的人都抱有暴力防卫心理。
- Paranoia is an instinct or thought process that is believed to be heavily influenced by anxiety or fear, often to the point of delusion and irrationality.[fn:2]

咱们再来看看妄想症患者的一些症状，请勿对号入座！
- Be easily offended \\
  容易激怒
- Find it difficult to trust others \\
  不信任他人
- Not cope with any type of criticism \\
  不接受任何批评
- Assign harmful meanings to other people's remarks \\
  对他人的评价做负面解读
- Be always on the defensive \\
  总是有防御心理
- Be hostile, aggressive and argumentative \\
  有敌意、好斗、好争辩
- Not be able to compromise \\
  不易妥协
- Find it difficult, if not impossible, to 'forgive and forget' \\
  很难原谅别人
- Assume that people are talking ill of them behind their back \\
  总觉得别人在背后说他坏话
- Be overly suspicious – for example, think that other people are lying or scheming to cheat them \\
  过度怀疑，总觉得别人在骗他耍他
- Not be able to confide in anyone \\
  不能与别人吐露心声
- Find relationships difficult \\
  难建立亲密关系
- Consider the world to be a place of constant threat \\
  认为世界是个充满威胁的地方
- Feel persecuted by the world at large \\
  认为世界上到处是迫害
- Believe in unfounded 'conspiracy theories' \\
  相信杯弓蛇影的阴谋理论


* Footnotes

[fn:1] A Pratical Guide to TPM 2.0

[fn:2] https://en.wikipedia.org/wiki/Paranoia
