#+BEGIN_EXPORT html
---
layout: post
title: 单词本：maverick
categories: [language]
tags: [English]
---
#+END_EXPORT

在一篇文章叫《Change is good - so get used to it》(改变是一件好事情，
要养成经常改变的习惯)中提到

#+begin_quote
we should make learning a way of life and ecourage mavericks. （我们
要学会将学习作为生活的一部分并且鼓励特立独行者的非主流想法）
#+end_quote

依稀记得，看书看新闻的时候，看到过好几次maverick，都没有留意是什么意
思。今天，在工作切换间隙，可以很清闲的学学新单词。

这个Maverick其实是一个姓氏，美国Taxas有一名律师和政客，叫做Samuel
Maverick(1803-7-23 ~ 1870-9-2)[fn:1]，这个人是 Texas Declaration of Independence 的签署者之一。
他年轻的时候有个农场，养了很多牛。按照行规呢，自家养的牛要给他打个烙
印（brand the cattle）。但是这个人要么是很懒，要么是对养牛不太感兴趣，
所以他们家的牛是不打印记的。慢慢的，周围的农场邻居们就管没有烙印的牛
叫 maverick。再后来，maverick演变为团体中不被信任的、非主流的、持不
同意见者、 独行其是者、言行与众不同者[fn:2]。

后来 Samuel Maverick把他的农场卖了之后，余生再也没有养过牛了。

例如：
- He was too much of a maverick ever to hold high office. 他太特立独
  行，永远不可能做高官。
- He made a maverick decision. 他做了一个特立独行的决定。
- She is such a maverick person. 她是多么特立独行的一个人啊。

* Footnotes

[fn:1] https://en.wikipedia.org/wiki/Samuel_Maverick

[fn:2] http://www.trivia-library.com/b/word-origins-and-the-biography-of-sam-maverick-part-3.htm
