#+BEGIN_EXPORT html
---
layout: post
title: 单词本：碳中和
categories: [language]
tags: [Deutsch, Français, English]
---
#+END_EXPORT

2021年政府工作报告中指出，中国将“扎实做好碳达峰、碳中和各项工作。制
定2030年前碳排放达峰行动方案。”“中国作为地球村的一员，将以实际行动为
全球应对气候变化作出应有贡献。”

“碳达峰”就是中国承诺在2030年前，二氧化碳温室气体的排放不再增长，达到
峰值之后再慢慢减下去；而到2060年，针对排放的二氧化碳，要通过采取植树、
节能减排等各种方式全部抵消掉，这就是“碳中和”。

法语 La neutralité carbone, c'est « l'équilibre entre les émissions
de carbone et l'absorption du carbone de l'atmosphère par les puits
de carbone »[fn:1] 德语 CO2-Neutralität.

英语 Carbon Neutral(Carbon Neutrality) - or Net Zero Carbon.  It is
a term used to describe the state of an entity (such as a company,
service, product or event, in the goverment report, the entity is a
country), where the carbon emissions caused by them have been
balanced out by funding an equivalent amount of carbon savings
elsewhere in the world.  These savings are generated through helping
to fund renewable energy projects and energy efficiency projects, as
a result to reduce greenhouse gases.

随着环保大众环保意识的提升，一个企业宣称其产品遵循碳中和策略，可以提
升其品牌知名度，获得更好的市场好感。

至于，减少二氧化碳的手段有：
- 碳封存 carbon sequenstration，主要通过土壤，森林海洋等天然碳收纳
  （natural carbon sink）吸收存储空气中的二氧化碳。
- 碳抵消 carbon offset，通过可再生能源和节能技术减少一个行业的碳排放
  量从而抵消另一个行业的碳排放量。抵消的量以二氧化碳当量吨数 carbon
  dioxide-equivalent计算。

碳中和需要各行各业共同努力才能达到，正如联合国秘书长 António
Guterres 说的 « La volonté d'atteindre la neutralité carbone doit
devenir la nouvelle norme pour tout le monde, partout - pour chaque
pays, entreprise, ville et institution financière, ainsi que pour
des secteurs clés tels que l'aviation, le transport maritime,
l'industrie et l'agriculture.  Tous les engagements en faveur de la
neutralité carbone doivent être appuyés par des plans clairs et
crédibles pour les atteindre ».

* Footnotes

[fn:1] https://www.hellocarbo.com/blog/calculer/la-neutralite-carbone/
