#+BEGIN_EXPORT html
---
layout: post
title: 单词本：soldiering
categories: [language]
tags: [English]
---
#+END_EXPORT

话说，第二次工业革命时期，科学技术发展突飞猛进，新技术新发明层出不穷，
工厂生产规模不断发展。相应的，对现代科学管理提出了更高的要求。这一时期
涌现了一批研究管理方法的学者。比如有精准分析工人作业动作的 Frank
Gilbreth，他把工人的标准操作分解为所谓 [[http://kimi.im/2021-03-11-english-therblig][Therblig]] 的 17 个动作，然后用秒
表进行计时进行动作优化。

照理说，把动作结构、优化、再组合，工人的工作效率应该很高才对。可是，事
实正好相反，反而是，越来越多的工人们消极怠工。这时候，有个叫 Frederick
Winslow Taylor 的人跳出来，说要解决这个问题。他后来被成为科学管理之父。
在钢铁厂工作的时候，泰勒发现很多工人通过破坏工具等方法，故意降低生产效
率。他将这种蓄意的工人们消极怠工、摸鱼、磨洋工的行为称为 soldiering：

Tayler witnessed many acts aimed at limiting or reducing production —
including having his tools destroyed — and it was he who coined the
term soldiering to describe this deliberate act. Working in the steel
industry, Taylor had observed the phenomenon of workers' purposely
operating well below their capacity, that is, soldiering. He
attributed soldiering to three causes [fn:1]:
- The almost universally held belief among workers that if they became more productive, fewer of them would be needed and jobs would be eliminated.
- Non-incentive wage systems encourage low productivity if the
  employee will receive the same pay regardless of how much is
  produced, assuming the employee can convince the employer that the
  slow pace really is a good pace for the job. Employees take great
  care never to work at a good pace for fear that this faster pace
  would become the new standard. If employees are paid by the quantity
  they produce, they fear that management will decrease their per-unit
  pay if the quantity increases.
- Workers waste much of their effort by relying on rule-of-thumb
  methods rather than on optimal work methods that can be determined
  by scientific study of the task.

他总结了工人之所以会 soldiering 的三个原因：
1. 工人普遍认为，工作太积极，活儿会干完，大家会失业。
2. 当时的薪酬系统不奖励工作效率的提升，工人担心太快地干活，会成为新的工作标准
3. 工作方法多以经验为主，没有进行科学的优化

相应的，泰勒提出了科学管理的四个原则：
1. 针对生产任务，以科学分析的方法替代经验判断
2. 科学系统的选择培训员工而不是放任不管
3. 协调工人们使用科学的工作方法
4. 协调管理层和工人进行工作分配，互相支持，合理激励

* Footnotes

[fn:1] http://www.netmba.com/mgmt/scientific/
