#+BEGIN_EXPORT html
---
layout: post
title: 单词本：tarnish
categories: [language]
tags: [Français, English]
---
#+END_EXPORT

还是从信息安全相关的书上看到的这段话：

When your reputation is *tarnished*, your finances are impacted, your
identity is stolen, your physical well-being is threatened, your
company's reputation and finances are harmed, and, quite possibly,
your country is overthrown, then you'll wake up to the need for cyber
security.

这里有个单词 tarnish，本意是失去光泽，在这里是指因为信息安全管理失误，
导致企业声誉变差。

tarnish 的本意是指金属表面的暗锈：

The tarnish is most commonly a silver sulfide tarnish, which is a
dense, black solid that results in the tarnishing layer on silver
jewelry and silverware. 银器表面最常见的暗锈是硫化暗锈。是一层密集的、
黑色固体状的暗锈层。

这个词来自法语 ternir，比如：

Quoi qu'il en soit, cette séquence ternit aussi l'image de la
diplomatie américaine. 如果那样的话，可能最终使的美国外交形象受损。

另外，还有生锈、铜绿：

Rust, tarnish, and patina all have numerous differences that can make
doorknobs, tables, windchimes, and many other items look completely
changed.

The differences between tarnish, patina, and rust are that rust is never an intentional occurrence, tarnish forms a glowing bronze tone on a few types of metal, and patina is a type of tarnish that usually shows up copper. Some homeowners use paint to make their metals show a tarnish or patina.[fn:1]

Rust 是指腐蚀导致的生锈，tarnish 是一层暗锈，patina 是铜表面的绿色锈迹。
人们经常会故意在金属物品上弄出暗锈和铜锈。

* Footnotes

[fn:1] https://azrust.com/rust-vs-tarnish-vs-patina/
