:PROPERTIES:
:ID:       4A3BAF76-324A-44E0-8F23-BC907DF21319
:END:
#+layout: post
#+title: 单词本：pro forma
#+categories: language
#+tags: English, Latin

前不久，公司 CMD 的 PPT。公司进行了一系列的财务优化，比如项目评估选择、
NWC 优化，ROC 不断提升，全球市场占有率也稳居第一。

PPT 中这些财务数据的标题叫做 2021 pro-forma。一看就知道这也是拉丁语。
字面意思就是“for the sake of form”，即形式上预估的意思。说白了就是，排
除财务上不确定因素、按照目前的经营效益进行预测估算。主要用来辅助制定财
务、经营方面的决策，或者跟投资人、股东沟通企业近期的经营效益。当然了，
作为公司员工，这些 pro forma 分析数据可以告诉我，我的年终奖大概在多少
范围。

在外贸行业，还有一种叫 pro forma invoice 的东西，预开发票。这个发票包
含了货物基本信息，用来评估物流价格、关税价格等。等到实际发货了，需要正
式开具发票替换。see：

A pro forma invoice is a preliminary bill of sale sent to buyers in
advance of a shipment or delivery of goods. The invoice will typically
describe the purchased items and other important information, such as
the shipping weight and transport charges. A pro forma invoice
requires only enough information to allow customs to determine the
duties needed from a general examination of the included goods.

在进行企业合并收购的时候，投行经常需要进行 pro-forma analysis，即预估
分析。分析合并收购会带产生多少商誉、收购会增厚还是摊薄净利润等，从而辅
助决策。

pro forma forecasting 的几个方法：
- percent of sales, 销售增长率。因为销售额和销售增长率是相关联的。
- straight line，直线拟合，假设在稳定市场情况下，年增长率上下浮动不大，
  那就可以大笔一挥，画出未来量三年的增长数据。
- moving average，移动平均。跟上面的假设类似，以前几年的财务数据做一个
  加权平均，预计未来的数据。
- simple linear regression，简单线性回归。根据历史数据，拟合函数方程式
  进行预估。
- multiple linear regression，多维线性回归。根据多个变量拟合曲线方程。
- delphi method，调研行业专家，统计他们对市场的预测进行预估。
- market research，市场分析研究。提出假设模型，验证假设，进行预估。
