#+BEGIN_EXPORT html
---
layout: post
title: 单词本：quid pro quo
categories: [language]
tags: [English, Latin]
---
#+END_EXPORT

上半年学了一套拉丁语课程。之后，就很容易在阅读文章的时候遇到拉丁语单词。
事实上，这些单词本来就藏在英语文章之中，只是以前没那么在意罢了。这个应
该是我们大脑神经系统的一种机能吧。因为我们的大脑每天要处理大量的信息，
信息处理的带宽是有限的，所以部分信息就会被过滤掉了。这就是认知过滤
（cognitive filtration）。这也就导致了我们人类不同个体认识世界会出现一
些差异，此谓认知偏差（cognitive bias）。只有不断的学习，获取尽量全面的
知识，才可以全面认识世界。

不扯远了。昨天在看工作包容性多样性（diversity in a organization），看
到这个词组 quid pro quo。这个是在讲办公室性骚扰指出性骚扰有两种形式：

Two forms of sexual harassment that can occur at work are *quid pro quo*
and hostile environment.
- Quid pro quo harassment refers to the exchange of rewards for sexual
  favors or punishments for refusal to grant sexual favors.
- Harassment that creates a hostile environment refers to behaviors
  that create an abusive work climate.

第一种就是 Quid pro quo harassment，是指通过职务之便给予报酬或惩罚索取
XX。另一种，则是简单粗暴的调戏他人。

前不久，SpaceX 的前空姐不就举报了 Musk：The attendant is reported to
have been a contract member of the SpaceX's corporate fleet. She
alleged Musk offered to buy her a horse as *quid pro quo* for an exotic
massage. [fn:1] 富豪说给她买一匹马，作为报酬，换取一次XX按摩。

If senior executives are allowed to engage in *quid pro quo*
relationships without getting sued or fired, then that's another
negative message. If true victims aren't believed and true
perpetrators aren't sanctioned with terminations or civil suits, then
the problem will continue. [fn:2] 如果企业允许高管用报偿获取好处，而不
被解雇，没人相信真正受害者，肇事者逍遥法外，那么问题会一直存在。

quid-pro-quo 本意是 something for something，一物换一物。比如
U.S. rejects Russian *quid-pro-quo* on Ukraine food exports. 俄罗斯以乌
克兰粮食解封换取解除制裁遭到美国拒绝。。


* Footnotes

[fn:1] https://www.rollingstone.com/culture/culture-news/elon-musk-space-x-flight-attendant-sexual-misconduct-settlement-1356164/

[fn:2] https://www.nbcnews.com/tech/tech-news/after-sexual-harassment-claims-uber-tesla-silicon-valley-prone-discrimination-n731236
