#+LAYOUT: post
#+TITLE: 单词本：Mazel
#+TAGS: Deutsch
#+CATEGORIES: language

9 月底是我们公司创新黑客松比赛的截止日期。作为参加了两届比赛的老选手，
我还是继续参赛。这次我们的参赛队伍扩展到多个产品研发部门。在确定参赛队
伍名称的时候，我提议找一个单词，包含四个组员的姓氏首字母：M，M，Z，L。
后来，我们找到了这个单词：Mazel。

这个奇奇怪怪的词语来自 Yiddish，意第绪语，也就是犹太语。它的本意是来自
上方的一点影响。或者说是，来自天空星座的影响力。是一种冥冥中的命运安排。
在英语里一般会把它和运气联系在一起。但是，其实上，它仅仅指的是一种命运，
命运可以是好的，也可以是坏的。

然后，常常和 Mazel 连在一起用的是 Mazel Tov，是祝你好运的意思。但是，
更多用于事后，比如当别人考试考满分，或者疾病痊愈从医院出来的时候，可以
用 Mazel Tov 向他祝福。而当运动员刚入场，或者某人生病刚入院的时候，则
不能用。

Mazel Tov 本意是一种灵魂之光。犹太人认为人的躯体里住着人的一丝灵魂，而
人的大部分灵魂其实是高高在上俯视着自己。可以类似的认为，我们在这个世界
上的身体，是某个 RPG 游戏玩家在显示器前操控着的游戏角色。游戏结束后，
这个游戏玩家可以选择再开一局，继续玩。如果以这种视角看待我们的人生，那
就要珍惜这次机会，好好打怪，把这一局人生的游戏完好，赚更多的金币，等下
次，可以玩更高级的装备。我们灵魂的主人也可以获得更多游戏的乐趣，才愿意
继续开一局玩下去。

那么，Mazel Tov 可以认为是我们肉体内的一丝丝灵魂和高高在上的灵魂主体建
立了一霎那的连接。就好像是 RPG 游戏中的角色跟游戏玩家的鼠标键盘操纵形
成了一种行云流水般的顺畅感。这是玩游戏的一个很享受的体验。

但是 Mazel Tov 体验不是随随便便就能获得，往往是在一些高光时刻，竞赛获
奖，生日宴会，大病初愈等时候，才会感受到。所以，Mazel Tov 就用来祝福这
种时刻，比如：

Mazel Tov on the birth of your lovely baby!

“Suddenly Rebbe Hersh hose, removed his white kaftan, and wrapping it
around the Maggid’s shoulders, wished him mazel tov, mazel tov,
congratulations. After a moment of surprised silence, all those
present joined in approvingly: Mazel tov, mazel tov, may the good star
accompany our new leader.” — Elie Wiesel, Souls on Fire: Portraits and
Legends of Hasidic Masters (1982)

Mazel Tov to Mazel team!
