#+LAYOUT: post
#+TITLE: 单词本：sine qua non
#+TAGS: English Latin
#+CATEGORIES: language

英国精神科专家 Anthony Storr 的研究认为，人类的亲密接触并不是幸福的唯
一来源，也不能促进人类的成长。他总结：Conversation enriches the
understanding, but solitude is the school of genius.  对话促进理解，但
是孤独是天才的学校。也就是说适当的与世隔绝可以促进人的思想进步。
Solitude can be just as important for both happiness and productivity.

所以 Storr's conclusion is that we're wrong to consider intimate
interaction as the *sine qua non* of human thriving.

这里，用到了英语拉丁文言文 sine qua non, 它的意思是“必要条件”。sine 是
英语 without, 法语 sans, 没有。 qua 是 qui 的 ablative 离格，夺格。就
是英语中的 which, 法语中的 qui.  non 就是 not.  合起来就是没有它则不行，
也就是必要条件，essential condition.

比如 Patience is a *sine qua non* for a good teacher. 做个优秀教师必不可
少的条件是要有耐心.

再比如 Tara Isabella Burton 写的一本书《SELF-MADE: Creating Our
Identities from Da Vinci to the Kardashians(创造自己：从达芬奇到卡戴珊)》
提到了巴黎时装客：

The Parisian dandies, who prized artistic creation as the “key to
human superiority,” sought to separate themselves from the foule, or
the masses. The *sine qua non* of the dandy was his ability to “cut
[himself] off from other people — their rules, their customs — and
show exactly how unlike other people one can be.”

巴黎时装达人追求与众不同，成为他们的必不可少的条件是把自己和他人区分开。
