#+LAYOUT: post
#+TITLE: 单词本：concur
#+TAGS: English Latin Français
#+CATEGORIES: language

Peter Cappelli 的 《The Future of the Office》
[[cite:&cappelli2021future]] 在介绍远程工作称为新常态时，写道：
Post-pandemic, many employees want to keep working remotely, but not
all employers *concur*. 后疫情时代，很多员工希望继续在家远程工作，但是并
非所有雇主都赞同。

这里，我们遇到个单词 *concur* ，它的意思是赞同、赞成。其实其本意应该是一
起发送、一起跑。

为什么这么说呢？

因为 con 其实是 com 的另一种写法，而 com 有是从拉丁语 cum 变来的。而
cum 是一起的意思。

cur 则来自拉丁语 currere，就是跑步的意思。法语里的跑步 courir 倒是和拉
丁语很接近。

那么，con + cur 就是一起跑。一起跑，就要目标一致，赞成的意思咯。

比如 Ron A. Carucci 在他的书《To Be Honest》[[cite:&carucci2021honest]] 中
说到作为 leader，在沟通一些负面评价的时候，尽管不赞成，也要做到同理心
共情：Be empathetic, though you don't have to concur or take action.

SAP 倒是有个企业差旅 APP 叫 concur，帮你提高出差、报销的流程。确实是一
个跟你一起出去跑业务的服务。

再举几个例子，比如 concurrent 就是 concur 的状态，并存的、同时发生的、
观点一致的意思。currency 就是在跑动的资金，流通的货币，就是通货。
current 就是跑动着的，就是当前流行的的么、最近的。

*References*
#+BEGIN_EXPORT latex
\iffalse % multiline comment
#+END_EXPORT
[[bibliography:~/docs/references.bib]]
#+BEGIN_EXPORT latex
\fi
\printbibliography[heading=none]
#+END_EXPORT
