#+LAYOUT: post
#+TITLE: 单词本：staycation
#+TAGS: English
#+CATEGORIES: language

信息安全运营专家 Gerald Auger 写了本书，介绍怎么从事信息安全事业。因为
搞信息安全工作的人，有时候不得不加班加点应对安全威胁，所以，他也提出了
一些建议，比如以下这些建议：

How do we find the perfect zen and balance? The following are things
to consider to avoid burnout [[cite:&auger2021master]]:
- Take breaks away from your computer.
- Go outside (with no technology).
- Don't bite off more than you can chew.
- Take a vacation if you can. It's essential to enjoy the love of your
  labor, so celebrate with a trip, even if it's a *staycation* in your
  home!

最后一条提到了要给自己放个假。哪怕是 staycation。我查了下，是这么说的：

a holiday spent in one's home country rather than abroad, or one spent
at home and involving day trips to local attractions.

所以，有两个意思：1）宅在家里不出门，阳台喝喝茶，晒晒太阳。2）在自己所
在的国家找个景点游玩下，而不是出国游。

我觉得，转换到中国的语境，home country 太大了，home city 就差不多了。

最近，天气这么好，适合来一场说走就走的 staycation！

*References*
#+BEGIN_EXPORT latex
\iffalse % multiline comment
#+END_EXPORT
[[bibliography:~/docs/references.bib]]
#+BEGIN_EXPORT latex
\fi
\printbibliography[heading=none]
#+END_EXPORT
