#+LAYOUT: post
#+TITLE: 单词本：excruciatingly
#+TAGS: English Latin
#+CATEGORIES: language

昨天读到这句话：

If you have spent most of your life being an overachiever, it is
*excruciatingly* likely that you are operating in a fixed mindset.

这里有两个词需要一些解释。

首先是 overachiever，意思是成绩超过预料的学生。也就是得到的成绩，超出
自己努力的付出的学生。一般，我们称这类学生为天才儿童。

另一个词是 excruciatingly 意思是极其痛苦、难以忍受的。

这段话的意思是说，一个大部分人生都是成绩超出自己努力，轻松获得好学生称
号的人，在他/她往后的人生中，会极其痛苦的发现自己是一个固定型思维模式
的人。固定性思维模式是心理学家 Carol Dweck 的经典作品《终身成长》这本
书中提出的。固定型思维模式的人认为聪明才智是天生的，后天努力无法改变，
于是认为人需要不断证明自己是天生聪明，害怕被批评，害怕冒险挑战自己不擅
长的，担心自己出丑，把自己限制在能力范围内行事，思想故步自封。

与固定型思维模式（Fixed Mindset），相对的是成长型思维模式（Growth
Mindset）。成长型思维模式的人相信人的能力是可以通过努力来发展的，头脑
和天赋只是自己才能发展的起点，而非终点，所以会一直保持学习，不断挑战自
己的能力范围，拓展自己的才能。

简单举个例子，比如说有个人经历了很糟糕的一天，德语考试分数出来了，100
分的卷子，发挥失常只得了 60 分。回家路上又遇到雷阵雨。不小心闯红灯，被
警察罚款。打电话给好朋友诉苦，又没人接听。

固定性思维模式的人会觉得自己德语不是自己擅长的方向，今后避免接触德语。
老天和社会都讨厌自己，连最好的朋友也看不起自己。考虑要不要跟这个朋友断
绝关系。

相反，成长型思维模式的人会分析考试出错的原因，出错的题目，指定改进计划，
加强学习巩固，下次争取个好成绩。以后留心观察气象预报，避免路上被淋雨，
骑车更加小心。顺路去朋友家看看，是不是遇到什么紧急情况，也许自己可以帮
上忙。

我们再回到本文主题：excruciatingly。这个词的动词形式是 excruciate 施加
酷刑、折磨。它是由 ex- 和 cruciate 组成的。cruciate 是十字叉形状的意思。
ex- 则是超出，穿过的意思。

那么合起来是指用十字叉形状穿过？拉丁语中 crux interpretum 指的是文中难
以解释费解的某个点。crux 可能指令人难以理解、折磨人的文字。再添加个
ex- 就是极其难以理解，极其折磨人的文字吧。

通常英语中折磨人是 torment 痛苦折磨，torture 拷问虐待逼供。我感觉，
excruciate 更偏向于内心灵魂的痛苦折磨。

所以，为了避免固定型思维导致的精神上的痛苦折磨，我们应该培养成长型思维。
按照 Carol Dweck 的书，有这么些方法：

- 认识自己的神经系统，大脑是具有可塑性的，人人都能学习成长。
- 欣赏学习的过程，而不仅仅是结果。
- 承认自己的弱点，努力改进自己的弱点。
- 培养自己的目标感，不断问为什么，思考自己学习工作的目的和意义。
- 把失败当作一次学习的机会，从失败和错误中学习。
- 重视努力而不是天赋。不追求“天才儿童”的称号。
- 不追求别人的认可，而应该追求学习提升自己本身。
- 把批评看作是他人的礼物，分析批评，改进自己。
