:PROPERTIES:
:ID:       02b3c1e0-0bab-4be1-aaa6-3d56fe2d9dc5
:END:
#+LAYOUT: post
#+TITLE: 单词本：pedal
#+TAGS: English
#+CATEGORIES: language

大部分钢琴都配有三个脚踏板，分别是：

- 左踏板
- 中踏板
- 右踏板

左踏板也被称作 soft pedal，即弱音踏板、柔音踏板。立式钢琴和三角钢琴的
左踏板工作原理不太一样。但作用差不多。都是通过移动钢琴音锤（hammer），
使得它只敲击三个琴弦中的一根，从而产生较轻的声音。所以，在意大利语里，
soft pedal 也叫 una corda，即一根弦。

在三角钢琴上，中踏板（middle pedal）则被称作保持音踏板、持续音踏板或保
留音踏板（sostenuto pedal）。在立式钢琴上，中踏板被称作弱音踏板。顾名
思义，这个踏板是能够起到弱化琴音的作用的。当演奏者在弹下一个音的同时踩
下中踏板，刚刚弹出的音就会有延音效果，但演奏者之后弹出的音却不会得到延
音效果。也就是说，中踏板只会使踩下时所弹奏的音对应的琴弦的制音器打开。
比如你弹 Rachmaninoff 的 Piano Concerto No. 3 的时候就非常需要这个
sostenuto pedal 的支持。琴谱上 sostenuto 保持音记号用小短横表示。

但是，在立式钢琴中，中踏板的作用只是在音锤和琴弦之间插入一层毛毡，从而
减弱声音，避免影响邻居休息。因此，立式钢琴的中踏板又叫 practice pedal。
或者你可以叫它：好邻居踏板！

右踏板（right pedal）又叫延音踏板、制音踏板（damper pedal 或 sustain
pedal），它在钢琴的机械结构里与制音器相连，能够控制琴音的延续与否。所
以当你踩下它的时候，琴弦声音就会一致延续，直到你松开 damper pedal，或
者直到你不小心睡着了，从琴凳上摔下来。


这个 pedal 是踏板的意思，它源自法语 la pédale 即 élément d'une machine
activé avec le pied. 机器上配合脚运动的组件。所以，你会发现法语 le
pied 脚和 la pédale 有不少相似的地方。

其实上，拉丁语里 pes 就是脚的意思。所以，英语里 pedestrian 就是用脚走
路的人，即行人。pedicure 足部保养。pedometer 计步器。
