#+LAYOUT: post
#+TITLE: 单词本：impetus
#+TAGS: Latin English
#+CATEGORIES: language

昨天看工业物联网时代的数字化转型，读到这句话：

Technological advances have been the *impetus* for dramatic increases in
industrial productivity since the dawn of the Industrial Revolution in
the 16th century. [[cite:&fcg2016dt]]

16 世纪的技术演进成为工业生产力大幅提升的动力。

这里我们看到有一个拉丁语单词 impetus。这个词是由 in + petere 组成的。
in 是朝向，petere 是攻击。合起来是朝着某处攻击。于是就引伸为动力、动量、
冲力。

比如，健身专家 Amaresh Ojha 在提到培养健身习惯的时候，说一个不清晰的健
身目标本身是无法提供改变现状的动力。要一点一点的进步： Once you make
the decision to launch your fitness habit, ... an ambiguous goal does
not, in and of itself, give you the impetus you need to change your
status quo. "Small progress everyday manifests bigger results in the
long run." [[cite:&Ojha2021fit]] 这里他也用到了之前介绍的 [[./2023-02-26-latin-status-quo.org][Status Quo]]。

再比如，Matthew T. Lawder 等 [[cite:&lawder2014battery]] 提到液流电池在储
能领域的发展，说这种电池在储能圈子获得了推动力：However, one battery
system that has gained *impetus* within the storage community recently
has been the RFB that uses exterior electrolyte pumped through the
typical cathode–separator–anode system.

市场消费者心理专家 Elizabeth C. Hirschman [[cite:&hirschman1982hedonic]]
在一篇关于享乐主义消费的论文中提到美观的产品能给消费者提供动力去发掘相
关产品，用到这个词：

This emphasis on esthetic products is constructive for several
reasons. First, it provides an *impetus* for exploring several classes
of products that have been largely ignored in traditional consumer
research.

*References*
#+BEGIN_EXPORT latex
\iffalse % multiline comment
#+END_EXPORT
[[bibliography:~/docs/references.bib]]
#+BEGIN_EXPORT latex
\fi
\printbibliography[heading=none]
#+END_EXPORT
