:PROPERTIES:
:ID:       53ADB451-5D41-4EC9-97E6-F41C9E423C65
:END:
#+LAYOUT: post
#+TITLE: 单词本：nonchalant
#+TAGS: English Français Latin
#+CATEGORIES: language

读到这句话：

My manager, though, seemed remarkably *nonchalant*. 我的经理似乎相当的漠
不关心。

这里 nonchalant  是冷淡的、漠不关心的、不感兴趣的意思。

这个词是从法语里来的。比如 La vivacité de son esprit démentait son
allure nonchalante.  他活泼的灵活和冷淡的外表互相冲突。

所以，在英语里，这个 nonchalant 要读成法语发音，大概类似去掉四声的“侬
想浪”。

另外，我们也知道，法语 non 是用来否定的，所以 chalant 就和冷漠相反，就
是不冷漠、关心的。

追根溯源，chalant 来自拉丁语 calere 取暖。所以，很多爱美人士每天控制的
卡路里 calorie 跟 calere 也是同源的，即 caloris。另外，这也是所谓的小
卡，而大卡，large calorie 则是 kilokalorie, 也就是千卡，小卡的 1000 倍。
大卡小卡容易搞错，所以科学家又定义了 joule 焦耳，用来表示大卡。其他相
关的词，还有，比如 calorifics 热学，calorific 发热的。

nonchalance 是 nonchalant 的名词形式。其实很多时候，能保持 nonchalant
是一种好的心理素质。千字文中说“容止若思、言辞安定”就是这种淡然自若、气
定神闲的 nonchalant ease 状态。这样，才能冷静决策，发挥良好。比如 She
defeated all her rivals for the job with *nonchalant* ease. 她从容不迫地
击败求职的所有竞争者。

在英语里还有两个词也表示冷静沉着，分别是 collected, 也是挺有趣的。我们
人的精神好像是一团气，如果你急躁、仓促，这团气就扩散，就像热力学第二定
律描述的，人的内心一旦燥热，就会蔓延出去，他的行动就会不理性了。所以，
要保持 cool 一点，nonchalant 一些。这样，才能凝聚精气神，也就是达到
collected 的状态。内心清凉了，自然就容易把自己的精神收集起来，不让它们
到处乱窜啦。《庄子》中讲的心斋大概也是这个道理：「若一志，无聽之以耳而
聽之以心，无聽之以心而聽之以氣。聽止於耳，心止於符。氣也者，虛而待物者
也。唯道集虛。虛者，心齋也。」这里说，唯道集虚。这个虚，大概就是到处乱
窜的发热的精神，而庄子所谓的道，就能把这个虚“集”、collect 起来。精神集
中了，就冷静沉着了，也就是 collected 了。比如 She always stays cool,
calm and *collected* in a crisis. 她在危难时总是很冷静、镇定如常、泰然自
若。
