#+LAYOUT: post
#+TITLE: 单词本：linkisch
#+TAGS: Deutsch
#+CATEGORIES: language

我们之前了解到，[[./2022-11-02-english-dexterous.org][dexterous]] 是双手灵巧的意思，而英语中 right 和德语中
recht 都有正确、合适的意思。

这次，我们来看看 recht 的反面，link。威廉·豪夫 Wilhelm Hauff 《豪夫童
话》中有一篇讽刺童话故事，叫做《Der junge Engländer oder Der Affe als
Mensch》（《年轻英国人或者作为人的猴子》）。故事讲的是一个魔法师厌倦小
镇的无聊社交活动，训练出了一只猴子参与到 Grünwiesel 小镇居民的无聊社交
活动中。（Grünwiesel 是不是绿黄鼠狼小镇？）

随着，扮演成英国小青年的猴子得到小镇居民的认可，小镇青年也开始向猴子学
习，变得庸俗粗鲁：

Als nämlich die junge Welt sah, wie derselbe mit seinem *linkischen*
Wesen, mit seinem rohen Lachen und Schwatzen, mit seinen groben
Antworten gegen ältere eher geschätzt als getadelt werde, daß man dies
alles sogar sehr geistreich finde, so dachten sie bei sich: »Es ist
mir ein leichtes, auch solch ein geistreicher Schlingel zu werden.«

这里，我们看到 linkisch 这个词，用来修饰 Wesen，是说绿黄鼠狼小镇青年
的笨拙的认知。

link 在德语里是左边，而 linkisch 是笨拙。是不是和 recht 形成鲜明的对比
呢？

德语和英语里 gauche 也有笨手笨脚、不擅社交的意思。而 gauche 在法语里正
是左边，英语的 left，德语的 link 。

大概，在右撇子主导的世界里，左撇子的行为习惯就显得很不合时宜、古怪、笨
拙了。

英语 awkward 就是尴尬、笨拙、别扭的意思。awkward 本来的意思也正是朝相
反方向转的意思。右边是恰当的方向，左边就是相反的方向了。所以
linkisch, gauche 就很 awkward.
