#+LAYOUT: post
#+TITLE: 单词本：flirter
#+TAGS: English Français
#+CATEGORIES: language

晚上看了讲法语历史的一篇文章 《La langue française : une longue
histoire riche d'emprunts》[[cite:&pruvost2010]] 其中提供英语中不少单词是
从法语里借过去的：

Leur prononciation ou leur orthographe les rendent cependant parfois
méconnaissables : qui reconnaîtrait spontanément dans « pudding », le
mot « boudin » ou dans « flirter », le français « fleureter, conter
fleurette »?

这里提到了 pudding 布丁，说是来自古法语 boudin，其实是香肠的意思。而法
语中的 pouding，其实是从英语里反借回来……

而 flirter 调情者则是借用了古法语的动词 fleureter 指的是说甜言蜜语。这
个词又是 fleur 鲜花的昵称 fleurette 转变过来。也可能比拟像蜜蜂一样一朵
花接着一朵花飞舞。

先有了 flirter 表示调情者、讲甜言蜜语的人。再有 flirt 就是调情、讲甜言
蜜语的动作。接着 flirtee 表示被调情的人。而 flirty 则是形容词：轻浮的。

有趣的是，现代法语并没有保留 fleureter，而是从英语里，又把 flirter 借
用了回去。比如：Il flirte avec une collègue de bureau. ❤️

当然，法语里也用 conter fleurette，比如：j’ai conté fleurette à la
plus belle dame.


*References*
#+BEGIN_EXPORT latex
\iffalse % multiline comment
#+END_EXPORT
[[bibliography:~/docs/references.bib]]
#+BEGIN_EXPORT latex
\fi
\printbibliography[heading=none]
#+END_EXPORT
