:PROPERTIES:
:ID:       CCD154D0-E341-4CD4-A4B3-1A92096348DD
:END:
#+layout: post
#+title: 单词本：sabotage
#+categories: language
#+tags: Français, English

最近看工业信息安全资料，读到这段：

#+begin_quote
Stuxnet attack managed to silently *sabotage* centrifuges in a
uranium-enrichment plant by reading and writing code blocks on PLCs
from a compromised engineering workstation.

2010 年震网攻击通过破防的工作站，修改 PLC 的代码块，偷偷的蓄意毁坏伊朗
的一个铀浓缩厂的离心机。
#+end_quote

这里有一个单词 sabotage，跟之前介绍的 [[./2022-11-03-english-triage][triage]] 的样子很像，也都是 -age
结尾的，也都是来自法语。

这个词的意思是 1）damage or destroy equipment, weapons, or buildings
in order to prevent the success of an enemy or competitor，通过蓄意破
坏设施、武器、建筑从而阻止敌人、竞争者。 2）to intentionally prevent
the success of a plan or action，阻挠某个行动或计划。

我饶有兴致地查了下 sabot 的意思：

sabot is a kind of simple shoe, shaped and hollowed out from a single
block of wood, traditionally worn by French and Breton peasants. There
are two kinds of sabots: one is shaped and hollowed from a single
piece of wood (called klompen by the Dutch), and the other is a heavy
leather shoe with a wooden sole.

大致来说，sabot 是法国农民穿的木鞋。一种是以整块木头雕刻的，一种是木鞋
底的皮鞋。顺便提一下，bot 在古法语里就是 boot（靴子）的意思。

最早的时候，sabotage 其实是一种相对温和的怠工行为：

SABOTAGE [chapter heading] The title we have prefixed seems to mean "scamping work." It is a device which, we are told, has been adopted by certain French workpeople as a substitute for striking. The workman, in other words, purposes to remain on and to do his work badly, so as to annoy his employer's customers and cause loss to his employer. [The Liberty Review, January 1907]

因为老板给的待遇不好，所以法国的工人们消极怠工，穿着 sabot 制造出噪音，
干扰客户，给老板造成损失。

后来不知道怎么的，sabotage 就成了蓄意破坏 malicious damaging or
destruction。

所以，saboteur 就是搞破坏的人，破坏分子。法语里还有 la saboteuse 女破
坏分子，但是似乎没有引入英语。例如：

These networks are exceedingly easy to detect and, with poor design
and architecture added into the mix, can be highly susceptible to
eavesdropping and masquerade attacks by the curious and *saboteurs*
alike.

此外，saboteur 还是一种人格类型：
- Saboteurs tend to be loners, not because they don’t like other
  people, but because they find it difficult to trust others.
- They are constantly afraid of being taken advantage of or betrayed.
- Saboteurs are often negative people who are always looking for the
  worst in every situation.
- They are quick to point out all of the faults in others and love to
  gossip about them behind their backs.
