#+LAYOUT: post
#+TITLE: 单词本：schedule
#+TAGS: English
#+CATEGORIES: language

早上看软件架构师主题的书，其中说到项目关系人/涉众的时候，提到管理层对
于架构的要求有预算、业务目标、产品质量以及项目进度：

keeping the development costs low, achieving business goals, being on
track with the development *schedule*, and maintaining product quality.

这里 schedule 虽然是一个很常用的单词，但是也有必要简单了解下。

众所周知，英语受法语影响很大，所以英语中的 schedule 其实是从法语里来的，
其法语来源是 cédule 其意思是欠条。

法语又是从拉丁语的 sedule 变来的。本意是写字的纸条。

稍微留意一下，我们可以发现其实德语的 Zettel 也是从 sedule 演变来的。
Zettel 就是德语纸条、卡片的意思。德国社会学家 Niklas Luhmann 就是通过
Zettelkasten 纸片盒笔记管理法，创作了著作等身的作品。Zettelkasten 也是
启发了很多有 backlink 反向链接的笔记管理软件的开发。比如我目前在用的基
于 Emacs 和 Org-mode 的 org-roam 插件。可以帮助我很好的管理我的学习笔
记。

至于，现代的作为进度表、日程表、安排时间等的意思，则是在 1863 年开始出
现，那时候的 schedule 是用于火车的时间表。

至于读音，英语沿用法语的读音，读作 ['ʃedju:l] ，而美国英语因为 Noah
Webster 的影响，沿用 schedule 的希腊语读音起源，读作 ['skedʒjul] 。

韦伯斯特字典可以认为是美国的新华字典，（英语：Webster's Dictionary），
为在美国被誉为“美国学术和教育之父”的辞典编纂者、拼写改革倡导者诺亚·韦
伯斯特（Noah Webster）编写的一系列字典。在美国，韦伯斯特的名字等同于
“字典”（通用商标），而他首版于 1828 年的现代《韦氏词典》尤为著名。现在
韦伯斯特字典多指美国梅里亚姆-韦伯斯特公司编写的字典。
