#+LAYOUT: post
#+TITLE: 单词本：pie in the sky
#+TAGS: English
#+CATEGORIES: language

最近韩国总统访问美国，跟美国总统合唱了一首《American Pie》，人民网记者
写了篇评论文章《Seoul's blind pro-U.S. diplomacy escalates regional
tensions》， 指出与美国套近乎，并不能帮助韩国提升 国际竞争力，文章结尾
写道：

"American Pie" only belongs to America; for others, it is nothing but
*pie in the sky*. 美国馅饼只属于美国，对于其他人来说只不过是天上掉馅饼。

这句话写的挺妙的。American Pie 是一首歌，同时也是一种食物。而天上的馅
饼则是一个英语俗语，意思是：something that you hope will happen but is
very unlikely to happen. 也就是天上的馅饼、天上掉馅饼、空头支票。

比如：Their plans to set up their own business are just *pie in the sky*.

*A pie in the sky* is like a castle in the air. 而 A castle in the air
is not built on firm ground. It's just a dream. 也就是空中阁楼。

那么 pie in the sky 的来源是什么呢？其实个词也来源于一首歌，作者叫 Joe
Hill，他出生在瑞典，1902 年的时候移民去美国工作。在那里，成了激进工人
组织（Industrial Workers of the World）的头头，写了很多激进的歌。其中
有一首叫《The Preacher and the Slave》，写于 1911 年，歌词内容如下：

From the day of your birth it's bread and water here on earth.

To a child of life to a child of life.

But there'll be *pie in the sky* by and by when I die and it'll be
alright it'll be alright.

There'll be *pie in the sky* by and by when I die and it'll be alright
it'll be alright.

主要意思是：我们现在就要面包过日子，不想死了在天堂吃到馅饼。

后来，拳王 Muhammad Ali 也引用过：You don't want no *pie in the sky*
when you die, you want something here on the ground while you're still
around. 你不会想要死后吃到派，你想活着的时候得到些东西。

后来，Joe Hill 被美国警察杀死了。
