#+LAYOUT: post
#+TITLE: 单词本：corpus
#+TAGS: English
#+CATEGORIES: language

最近工作真是忙，晚上好多在线会议，都没时间好好看论文文，写文章了。昨天
看到个知识图谱（Knowledge Graph）相关论文（ [[cite:&valeria2018fact]]），
其中提到现行的大部分知识挖掘模式：Most of existing computational
approaches (e.g., [Zubiaga et al., 2017; Hassan et al., 2017]) detect
facts in large corpora (e.g., the Web, Twitter) and leverage
indicators (e.g., tweet popularity) and other (mostly syntactic)
features to measure their credibility.

这里，我们看到一个单词，corpora ['kɔ:pәrә]，意思是“事物之全体”。它的单
数形式是 corpus 。其实 corpus 的本意是身体器官的主要部分结构，引伸意是
文学作品的全集，比如 he edited the Lu Xun corpus. 他编辑了鲁迅全集。

corpus 这个词来自拉丁语，意思就是身体。从这个词衍生来的还有以下这些：

corps 军团、军队、学生联合会、团队。这个词应该是从法语里来的，所以ps
是不发音的，读若 [kɔ:]。例如 the Diplomatic Corps 外交使团；the press
corps 记者团。以前我介绍过亨利·法约尔提出的14条管理原则中有一条就是[[./2021-03-12-francais-esprit-de-corps][团
队精神原则（esprit de corps）]]。这个法语词组中的 corps 就是团队的意思。
例句：Working and collaborating together builds a camaraderie and
esprit de corps.

corpse 则是尸体的意思。这个词的 pse 倒是要发音的，读若 [kɔ:ps] 。以前
有个动画片叫 Corpse Bride 僵尸新娘。瑜伽动作 corpse pose 平躺在地，两
手摊开，状若尸体。corpse candle 尸体蜡烛，即鬼火。

corpuscle 小体，微粒，如原子、电子、细胞、红白血球之类。

corpulent 肥大的，肥胖的。-ulentus 表示满满的，身体满满的，就是肥胖肥大的。

corporal：身体的。corporal punishment 身体的惩罚，体罚。

corporeal：肉体的，相对精神而言。corporeal needs 维持身体的必需品，He
is very religious, corporeal world has little interest for him. 他信奉
宗教，对物质世界不感兴趣。

corporate：全体的组织。公司法人团体。

德语里，c 一转而成 K，Körper。der Körper 是身体的意思。比如 Beim
taijiquan bewegt man sich sanft und lansam; das ist gut für Körper und
Geist. 通过柔和舒缓的伸展运动，太极拳可以帮助人们提升身体和精神健康。

在比如，庄子齐物论中顏成子游跟老师说的：何居乎？形固可使如槁木，而心固
可使如死灰乎？Können wir wirklich bewirken, dass der *Körper* wie
verdorrtes Holz und der Herz-Geist wie kalte Asche wird?

形容词形式为 körperlich，比如 Jungen erhalten oft Namen, deren
Bestandteile *körperliche* Gesundheit und Stärke bedeuten, wie
z. B. Kang, Jiang, Qiang. 中国的年轻取名字注重身体健康与强壮，所以很多
以康、健、强取名。

大概因为拉丁语里 -us 都是阳性名词的结尾，所以神圣罗马帝国延续下来的德
语中 Körper 也是一个阳性词。

#+BEGIN_EXPORT latex
\iffalse % multiline comment
#+END_EXPORT
*参考文献*

[[bibliography:~/docs/references.bib]]
#+BEGIN_EXPORT latex
\fi
\printbibliography[heading=none]
#+END_EXPORT
