#+LAYOUT: post
#+TITLE: 单词本：lip service
#+TAGS: English
#+CATEGORIES: language

讨论可持续发展的一本书 "Work to Restore" 中写道：

Business has the power to affect the enormous challenges facing
humanity, including social justice, climate change, water shortages
and famine. But it will take more than *lip service* made up of mission
statements and inspirational quotes.

商业对我们面临的人道主义挑战有很大的影响力，这些挑战包括：社会公平、气
候变化、水资源短缺以及饥饿问题等。但是，我们所要做的可不是一些使命陈述
或激励人心的名言警句之类的风凉话。

大家看到，这里有个词组 lip service，字面意思是“嘴唇服务”，看起来真是丈
二和尚摸不到头脑。其实，在英语中，lip service 指的就是动动嘴皮子，说说
风凉话，光说不做，画饼充饥之类的意思。

比如 The UN through its assistance to some of the smallest countries, is
again showing that its commitment to Leaving No One Behind (LNOB) is
much more than *lip service*.

lip service 一般会搭配一个动词 to pay *lip service* to something，比如说：

She claims to be in favour of training, but so far she's only *paid lip
service* to the idea.

It is all too easy to *pay lip service* to human rights.

德语里，嘴唇是 die Lippe，所以他们管 lip service 叫 Lippenbekenntnis，
Bekenntnisse 是自白，表白，表明信仰的声明的意思。那么 pay *lip service*
to something，就表达为 ein *Lippenbekenntnis* zu etw. ablegen。

另外，嘴唇是用来讲话的，所以 *None of your lip* 就是闭嘴，别插话的意思。

哦，对了，还有 read my lips，是“听好了”的意思。因为最说话的时候，嘴唇
会动么，让别人看着你的嘴唇，就是让别人注意听好了你说的话。当然，这里可
能有些不太礼貌比较唐突，命令别人的感觉。

比如：forget about him, *read my lips*, he wasn't worth it.
