:PROPERTIES:
:ID:       292203B9-DF85-48A2-ACB0-57558750273B
:END:
#+LAYOUT: post
#+TITLE: 单词本：intractable
#+TAGS: English
#+CATEGORIES: language

最近我们干了个大事情，拉拢巴勒斯坦16个党派，签订了合作框架《北京宣言》。
西方网友是这么评价的：

China is the land of grandmaster diplomats. Fixing the *intractable*
political conflicts manufactured by the Anglo American Empire one by
one.

*intractable* ：倔强的、棘手的、难治疗的。

它源自拉丁语 intractabilis 难处理的。in- 前缀表否定，tractabilis 可处
理的。

举几个例子：

(CNN) — As a border crisis unfolded only months into Joe Biden's
presidency, he looked to his vice president to help solve an
*intractable* issue: migration. 拜登推选，转向希望哈里斯解决移民这个棘手
问题。[fn:1]

A few of the research topics recently garnering my attention are
psychedelic-assisted therapies for *intractable* psychiatric conditions,
interactions between the immune system and brain function, and
computational approaches that promise to usher in elusive predictive
and diagnostic markers for psychiatric conditions. [fn:2]

*Intractable* pain, also called *intractable* pain syndrome (IPS), is a
severe, constant, relentless, and debilitating pain that is not
curable by any known means and which causes a house-bound or bed-bound
state and early death if not adequately treated, usually with opioids
and/or interventional procedures. 维基百科上介绍得难治疗的疼痛症。[fn:3]

tractabilis 来自拉丁语动词 tractare 处理、管理。对应的英语动词是 treat
处理 。形容词 tractable 意思是顺从的、驯服的、易处理的。

而 tractare 又可能来自 trahere 强力拖拉。拉丁语 trahere 的过去分词是
tractus 。

trahere 对应英语是 drag 拖拉。而 tractus 对应的英语 tract 表示大片的土
地、通道，可能也可以理解为从地上拖拉出来一块地、拖拉的通道。

tracts of natural forest 大片大片的天然森林

the digestive tract 消化道，the respiratory tract 呼吸道 [[cite:&appledict]] 

respiratory 可以参考我们之前学过的[[id:C4DCC461-D06C-4036-A29F-2A81FA5FA64C][单词本：aspiration]]，来自拉丁语 ad +
spirare，ad 是 to，spirare 是呼吸。所以 aspire 的本意就是朝这最远的地
方呼吸，即渴望、有志向于某事。

*References*
[[bibliography:~/docs/references.bib]]

* Footnotes

[fn:1] Harris’ immigration work comes under scrutiny as campaign takes
shape. https://www.krgv.com/news/harris-immigration-work-comes-under-scrutiny-as-campaign-takes-shape/

[fn:2] Looking Toward the Future in Psychiatry: A Medical Student’s Perspective. https://www.psychiatryonline.org/doi/full/10.1176/appi.pn.2024.08.8.26

[fn:3] Intractable pain. https://en.wikipedia.org/wiki/Intractable_pain
