#+LAYOUT: post
#+TITLE: 单词本：beef
#+TAGS: English
#+CATEGORIES: language

工业设备的通信接口一开始使用 4-20mA 的电流信号，后来，为了解决信号变量
传输太少的问题，上世纪 80 年代，人们想到了个办法，在 4-20mA 的电流信号
上叠加一个所谓的 FSK 频移键控信号，使得模拟信号和数字信号互不干扰在同
一根物理导线上传输。频移键控就是设定两组不同的信号频率表示数字信号比特
位 0 和 1 。这种协议就叫 HART - Highway Addressable Remote Transducer。

然而，速度还是一个大问题：

Indeed, the biggest *beef* against 4-20mA HART has always been speed,
making configuration and other tasks both time-consuming and
cumbersome.

这里，用到了 beef 这个单词。看起来好像毫无关系。关于 4-20mA HART 总线
最大的牛排是速度？

其实，这个 beef 是 complaint 抱怨的意思。

所以，这句话是说人们对 4-20mA HART 总线最大的抱怨总是速度问题，配置设
备、检查设备数据总是要花很多时间，一来一回又很繁琐。后来的解决方案是
HART-IP。

beef 来自法语的牛肉 boeuf，然后，更早源自拉丁语 bovem 牛。英语里
[[./2016-08-11-english-bovine][bovine]] 正是“和牛相关的”之意。比如牛郎织女故事里介绍的：

The cow, however, was a former god who had violated imperial rules and
was sent to earth in *bovine* form.

还有 bull 公牛，bovid 牛科动物。

那么，牛肉怎么就和抱怨有关呢？

据说是美军娇生惯养，曾抱怨牛肉供给的数量和质量不好闹了很大的事情，所以
被抱怨对象成了抱怨本身。

而且，beef up 增加牛肉，在口语表示增大、扩大的意思。如：Please beef up
the budget! 请增加预算！

北京话“别逼逼”，意思就是别废话了，语气里沾着北京地地道道的优越感，就是
让你别瞎扯了，大多带着不屑听，不屑你说的意思。不知道是不是从 beef 来的？
别 beef beef 了？
