#+LAYOUT: post
#+TITLE: 单词本：villain
#+TAGS: English
#+CATEGORIES: language

前几天在 Emacs 开源社区论坛看到开源大佬 manateelazycat 分享的技术升华
经验。他推荐大家看《练习的心态》 [[cite:&sterner2012practicing]] 。这本书
是钢琴调音师 Thomas Sterner 在多年练习钢琴、练习高尔夫球、给钢琴调音的
工作学习实践中，总结出的生活经验。当我们能跳出对自己对他人对正在做的事
情的进行评价的习惯，从一个旁观者的角度看待这些事情，就能够摆脱情绪的影
响，从而专注眼前做的事情，更慢，却更好的提升技能。在提到情绪对运动练习
的影响时，Sterner 写道：

It's a game of sorts, and you are not letting the *villain* of emotions
play in your game. Soon the enjoyment that you experience from staying
in the present moment will make hitting the target smack in the middle
irrelevant. 

意思是，当你以一个旁观者的角度观察自己的练习时，就能摆脱情绪这个恶棍的
影响，从而享受当前时刻练习的快乐，不断调整，从而提升自己的技能。

这里用到的单词 *villain* 是恶棍、歹徒、坏人、淘气鬼、坏蛋的意思。比如：
- get off my car, you little *villain*! 你这个淘气鬼，快离开我的车子。
- A faulty fuse was the *villain of the piece*. 毛病就出在这个坏掉的保险
  丝上。 villain of the piece 连在一起指惹祸的、为害的人或物。

这个词最早原子拉丁语 villa 乡村别墅、农场。

而拉丁语 -anus，-nus 表示来源、属于的意思，比如 Roma 是罗马的意思，而
Romanus 则是罗马人；Christus 基督，而 Christanus 则是基督徒。同样的，
villanus 则表示来自农场的，即农民。

后来，到了法语里，就变成了 vilain，农民、平民、农夫的意思。这时候还没
太多贬义。

之后，大概 1300 年，vilain 从法语走到英语里，成了 villain ，意思变成了
小丑、无赖、守财奴、恶棍的意思了。villain 就成了一个 pejorative 贬义词。

相关的还有
- villainous 恶棍似的、邪恶的、糟糕的
- villainy 极其坏的事情
- villainage 农奴身份、农奴地位
- villainess 阴性词：女恶棍、女反派

*References*
[[bibliography:~/docs/references.bib]]
