#+LAYOUT: post
#+TITLE: 单词本：enchanter
#+TAGS: English
#+CATEGORIES: language

春节快到了。公司又能开年会了。这次年会，我们外语文化学习小组表演诗歌朗
诵，雪莱的《西风颂》。

诗人是文字游戏高手，所以选词造句都是很精妙的。所以，西风颂里很多单词，
我们都感觉很陌生。

第一节的前两段是这么写的：

#+begin_verse
O wild West Wind, thou breath of Autumn's being,
Thou, from whose unseen presence the leaves dead
Are driven, like ghosts from an *enchanter* fleeing,
#+end_verse

我试着翻译下

#+begin_verse
啊！狂野的西风。你是秋灵的呼吸，
你，用无形的威力，把枯叶驱使，
像孤魂野鬼从法师处逃离。
#+end_verse

或者翻译的文诌诌一些

#+begin_verse
呜呼，西风飙兮，其秋之噫气，
隐其无形兮，驱败叶，
若孤魂兮，自尸祝而逃匿。
#+end_verse
    
这里，enchanter 的意思是行巫术的人、巫师、魔法师、使人着迷的人。

因为，这个词来自法语，所以保留了一些些法语的调调 [in'tʃɑ:ntә]。
enchanter 是 en + chant + er 组成的。en 是进入，chant 是歌唱。大概是能
唱出美妙歌声，让人入迷的那种人。来自拉丁语 incantator。

其他类似意思的还有
- sorcerer
- magician
- wizard
- necromancer

sorcerer 来自中世纪拉丁语的 sortarius 算命的人。漫威漫画中有至尊法师
sorcerer supreme。歌德有个诗作《Der Zauberlehrling 魔法师的学徒》，这
里 Zauber 就是魔法的意思，好像和 sorcerer 有点点相似。

magic 来自希腊语 magos: person with magic powers. magic 的意思可以是魔
力，魔法，妙不可言。比如 Her piano playing is absolute *magic*. magician
是施展 magic 的人，就是变戏法的人、魔术师。

wizard 是男巫，这个来自古英语 wys + ard，wys 是 wise 聪明的意思，所以
是聪明的巫师。绿野仙踪翻译自 Wizard of Oz 或者奥兹国历险记。

necromancer 是通灵人，指那种擅长黑魔法的巫师。
