#+LAYOUT: post
#+TITLE: 单词本：butterflies in the stomach
#+TAGS: English
#+CATEGORIES: language

多年前参加一个学习培训，得到了一本《Dare to lead》作为奖品。一直放着忘
记看了。今天拿出来看下。

Brené Brown 在扉页说自己是个很容易紧张的人，公众演讲的时候进场紧张得不
行。因为她觉得听她演讲的人提供了自己宝贵的时间给她，而她却一点不紧张那
是不负责的态度。

原文这么写的：If being on the receiving end of one of life's most
valuable gifts fails to leave you with a lump in your throat or
*butterflies in your stomach*, then you're not paying attention.

这里出现了两个描述紧张的词组。

第一个是 with a lump in your throat 喉咙里有一个团块。也就是 be
swelling in your throat。紧张地要哽咽了。

第二个是 with butterflies in your stomach 千万蝴蝶胃中舞。也表示紧张的
感觉。

总之，紧张确实可能会导致消化系统痉挛。记得以前看到过新闻说有人山中看到
蛇，惊吓后回来发现肠道出血。不知道是不是真的。薇琪妹妹参加钢琴比赛前，
也会紧张的想吐。

追溯源头看，最早是 1908 年美国作者弗洛伦斯·康威斯在《The House of
Prayer》中用到过这个隐喻：The three o'clock train going down the
valley […] gave him a sad feeling, as if he had *a butterfly in his
stomach*. 但表示的是不开心的感觉。

1937 年佩吉·哈丁的文章中描述了刚加入校园联谊会成员的紧张心情用到
have pink butterflies all over my stomach：

With a great display of vivacity one rushee popped "I'm so nervous I
feel that I have *pink butterflies all over my stomach*."

1941年《The Oregonian》中的滑雪比赛新闻中描述俄勒冈小朋友的紧张心情：

The Oregon kids had "*butterflies flopping around like eagles*" when
they made their first runs. But they soon got over their nervousness
and found that it was easier to ski on these slopes than on the
flatter ones they were used to.

这里更夸正地描述成蝴蝶像老鹰一样拍打翅膀。

总之，现在蝴蝶在胃里也好，在周围也好，都表示紧张的感觉：

I'm meeting her parents tonight, and I have a bad case of *butterflies
in my stomach*.

*The butterflies in my stomach* almost kept me from going on stage and
performing.

*The butterflies in my stomach* are really bad, Mom. I don't think I can go out there and pitch.

Even though I'm student council president, I always get *butterflies in
my stomach* before I have to make announcements in front of the whole
school.

还有扩展出来多个不同的版本：

Jennifer says she *doesn't get butterflies down* at the start is
telling lies. 珍妮弗说她说话的时候就没法把蝴蝶打下来。

Carol felt *butterflies tumbling in her guts*. 卡萝尔感觉蝴蝶在肚子里翻滚。

Some of the kids *had butterflies* before the school play.

Even after 15 years of performing in front of an audience he still
*gets butterflies* before a show.
