#+LAYOUT: post
#+TITLE: 单词本：pseudonym
#+TAGS: English
#+CATEGORIES: language

最近涉猎了不少信息安全相关的文章，在隐私计算方面，Wang Zhigao 等人
[[cite:&wang2024blockchain]] 提出了一种利用区块链进行设备鉴权的匿名算法：

We design an anonymous authentication algorithm that achieves an
efficient trade-off between the computational overhead and storage
overhead of smart devices.  In particular, the smart device can update
*pseudonyms* by itself without sending *pseudonym* update requests to the
domain authorization center and pre-storing massive *pseudonyms*.

*Pseudonym* certificate-based authentication can guarantee device
anonymity and is lightweight, so it is often used to authenticate
devices with limited computing power.

他们用了假名证书来进行互相真实性验证。

这里，他们用了 pseudonym 假名、笔名。这种 ps 开头的词，很多都是从希腊
语来的。比如 psychology。pseudo 源自希腊语 pseudes 假的，onym 则来自
onuma 也就是 name，合起来就是假的名字。

pseudonymous 即形容词：用假名的。比如 his books are pseudonymous. the
pseudonymous author of this mystery.

那么 homonym 的意思呢？这个词是指那些发音一样、拼写一样但是意思不一样
的词语。

前面看到的 anonymous 中，因为 an 是没有的意思，所以 anonymous 就是匿名
的意思了。

*References*
[[bibliography:~/docs/webref.bib]]
