#+LAYOUT: post
#+TITLE: 单词本：attain
#+TAGS: English
#+CATEGORIES: language

Don Hellriegel 等人 [[cite:&hellriegel2005ob]] 的组织行为学一书中介绍了
David McClelland 的成就激励模型，提到成就高的人通常不会选择极难的目标，
也不会选择极易的目标，而是选择难度适合自己的目标。这就是孙子所说的知己
知彼百战不殆。

High achievers avoid selecting extremely difficult goals. They prefer
moderate goals that are neither so easy that *attaining* them provides
no satisfaction nor so difficult that *attaining* them is more a matter
of luck than ability. They gauge what is possible and then select as
difficult a goal as they think they can *attain*.

这里用到 *attain* ，意思是实现、达到。它源自拉丁语 attingere，ad-/at- 前
缀表示 at，to；tangere 表示触及。触及到，就是达到了。

Don Hellriegel 还写道：

Employees should think about setting realistic goals and the ways that
they can *attain* them.

员工应该考虑设置一个现实的目标和方式，这样他们就能实现这些目标。我们平
时学习工作中，应该给自己设置一些能力所及的目标，一个一个地完成这些小目
标，等到回头看，已经走了很远了。

比如，我从三年前就设定每年提交三个专利申请的小目标，这几年每年提交三到
四个专利，累积下来已经有七八个国际专利提交专利局公示了。昨天，公司的专
利创新评审部门已经邀请我去评审别人提交的专利。也就是说，我从一个创新者
成为了一个创新评审者。这是我从来没有想到的。三年前面对全公司各个业务部
门的技术老大介绍自己的专利紧张得很，没想到，现在我成了他们一员去评审别
人的创新想法了。

*References*
[[bibliography:~/docs/references.bib]]
