#+LAYOUT: post
#+TITLE: 单词本：voraussichtlich
#+TAGS: Deutsch
#+CATEGORIES: language

昨天，学了个单词 [[id:E2092812-E43C-4772-A899-F7F610C31388][zuversichtlich]]，意思是自信，因为看见所以自信。

这里，我们又遇到了一个 sichtlich 结尾的形容词 *voraussichtlich* ：

Biden - mit seinen 81 Jahren der älteste Präsident der US-Geschichte -
hatte bei der TV-Debatte mit seinem *voraussichtlichen* Herausforderer
Trump im Sender CNN in der vergangenen Woche mit heiserer Stimme
gesprochen, sich wiederholt in seinen Formulierungen verheddert und
Sätze nicht zu Ende gesprochen.

*voraussichtlich* 的意思是可预见的，expected，潜在的。这里说 Trump 是
Biden 的 *voraussichtlich* Herausforderer 潜在的挑战者。

*Aussicht* 是 view, prospect 景色、景象的意思。

*Voraussicht* ：vor = fore 前面的，sicht = sight 视线，所以，
*Voraussicht* = foresight 在前面的景象，也就是眼前所见的景象。

也就是远见、先见之明。

那么 *voraussichtlich* 就是可预见的 expected.

Das Flugzeug wird *voraussichtlich* mit einer Verspätung von 20 Minuten
eintreffen. 飞机估计要延误20分钟。

Sie bewertet ihre Villa *voraussichtlich* mit einer Million Yuan. 她估算
她的小别墅值100万。

拜登和特朗普的电视辩论非常精彩。我是指从逗乐角度来说非常精彩。拜登 81
岁高龄，还能讲完一个半小时的稿子已经很不容易了。
- 声音嘶哑 mit heiserer Stimme
- 不断重复 sich wiederholen
- 含糊不清 Formulierungen verheddert
- 话说不完整 Sätze nicht zu Ende gesprochen

然而，美国民主党政客依然挺拜登："Wir haben gesagt, dass wir an seiner
Seite stehen werden", sagte der Gouverneur des Bundesstaats Maryland,
Wes Moore

看来，还能以后再看拜登逗乐的演讲了。
