#+LAYOUT: post
#+TITLE: 单词本：judicious
#+TAGS: English
#+CATEGORIES: language

这两天有个瑞典有个老专家过来给我们做功能安全开发培训。老专家果然是老专
家，功能安全标准哪一页哪张表都能记到脑子里。还打趣的说，等你们也能记住
这些细节的时候，就离死不远了。

功能安全和产品功能在经济价值相比，显然有点出力不讨好。但是，对于那类出
错了，就要付出沉重代价的领域，功能安全是不能少的。比如 TüV 的功能安全
手册里这么说：

There is strong evidence to support that a wise and *judicious*
investment in safety is a indeed a value add. Investment in safety
will have a direct positive impact on the bottom line. One extremely
important factor in the value add is management of risk.  Functional
safety represents the absence of unacceptable risk from hazards caused
by systems' malfunctioning behavior.

功能安全的投资是明智的。最重要的是能做到风险管理。功能安全就是把无法承
担的风险发生的概率降到能接受的范围。

这里，用到了 *judicious* ，意思是有见识的，明智的。比如 a *judicious*
choice, a *judicious* decision, a *judicious* remark.

这个词其实和 judge, judgment 同源，即有判断的意思。拉丁语里判断就是
iudicium。形容词形式为 iudiciosus。动词为 iudicare 。

再拆分开，ius 是公正、法律的意思。dicere 是说的意思。加起来，就是把公
正和法律说出来，即审判、判决。

Businesses can increase their bottom line by a *judicious* spend on
safety.

那么，反义词就是 injudicious 判断不当的、考虑不周的、不合适的、不明智
的、浅薄的。

In this big environment, it is an *injudicious* moment to ask for a
rise. 在现在这个环境，要求加薪不是个明智的时候。

Lu Bu betrayed Ding Yuan is an *injudicious* decision. 吕布背叛丁原是个
考虑不周的决定。

法语和英语同源，judicieux。其实可以认为英语是从法语里学去这个词的。

德语近义词是 umsichtig 大概就是眼睛看得清、明智的。

Waymo betont, dass die Software sicher sei und die Wagen
*umsichtig*. Weymo 自动驾驶公司强调他们的软件是安全的，汽车是智能的。
