#+LAYOUT: post
#+TITLE: 单词本：Der Geist ist willig
#+TAGS: Deutsch English
#+CATEGORIES: language

今天介绍圣经里的一句短语 Der Geist ist willig, aber das Fleisch ist
schwach. 心灵固然愿意，肉体却很虚弱。也就是心有余而力不足。

圣经里是这么写的：耶稣·基督在与 12 门徒共进最后的晚餐之后，他们唱了诗，
往橄榄山去，来到客西马尼园（Gethsemane），耶稣对门徒说：“你们坐在这里，
等我祷告。”于是带着彼得、雅各和约翰同去。预感到自己将死，耶稣心里非常
难过，他对三个门徒说：“我心里难过得要命，你们在这里，等候警醒。”耶稣稍
往前走，俯伏在地，祷告上帝。等他回到三个门徒那里，发现他们都睡着了，
就对彼得说：“你们不能跟我一起警醒一个钟头吗？要警醒祷告，免得陷入迷惑。
你们心灵固然愿意，肉体却是软弱的。当耶稣第三次祷告回来，见他们仍然睡着，
就对他们说：“现在你们仍然睡觉安歇吧。时候到了，人子被卖在罪人手里了。
起来，我们走吧。看哪，卖我的人近了！”

这里耶稣老师让三个门徒醒着等他，结果三个都睡着了。他就说了这句话。在我
们的论语里，孔子也批评过白天睡觉的宰予：

宰予昼寝，子曰：“朽木不可雕也，粪土之墙不可圬也！于予与何诛？”子曰：
“始吾于人也，听其言而信其行；今吾于人也，听其言而观其行。于予与改是。”

这里，孔子批评的算得上是非常严厉的了。所以说，古代的先师们还是很注重学
生是否勤劳的。不勤劳的学生是要被严厉批评的。

举一个例子：

Seit Monaten will ich mich schon bei Ihnen melden, leider war nur *der
Geist willig aber das Fleisch schwach*. 意思是我没能按时提交报告。

英语里则翻译为 the spirit is willing, but the flesh is weak. 并且前后
半句可以分开单独使用。

比如：

I wish I could stop smoking; *the spirit is willing, but the flesh is
weak*. 言下之意，就是我没能戒掉抽烟。

Sorry I can not give you the job. To tell you the truth, I am not the
one who have the last word. *The spirit is willing but the flesh is
weak*. 意思是我力不从心，帮不上你了。
