#+LAYOUT: post
#+TITLE: 单词本：collude
#+TAGS: English
#+CATEGORIES: language

今天看了远程设备认证的一个综述论文 [[cite:&banks2021ra]] ，远程设备认证
remote attestation 就是通过对设备提供的运行时记录，验证设备上运行的程
序是否被篡改。设备远程认证，又分为基于软件的认证，基于硬件的认证和混合
认证。基于软件的认证假定针对认证过程的攻击不能利用现场的其他设备。也就
是攻击者不能有近场的设备可以合谋。如果攻击者能串通控制现场的设备，就很
容易绕开软件认证协议，对验证方进行欺骗了。

Software-based attestation protocols guard against these attacks by
relying on the assumptions that adversaries cannot *collude* with other
devices, that the checksum and attestation code cannot be optimized
further and that the attestation cannot be parallelized.  The
assumptions made by the attestation protocols defends against the
adversaries. However if *collusion* is possible a local adversary would
have the advantage of lower latency’s in the network.

*collude* 就是合谋、勾结、串通的意思。

*collude* 源自拉丁语 colludere，co 就是 com- 也就是一起的意思，ludere 是
玩的意思。ludicrous 可笑、荒唐，就是从 ludere 衍生来的。

这里，我们看到了语言含义的变迁。本来是很开心的一起玩，随着时间推移，成
了合谋、勾结。

要么，这么理解，一起玩，就是猨猵狙以为雌，麋与鹿交，鳅与鱼游
[[cite:&zhuangzi]]，狼狈为奸。就是一起干坏事的人。

引文里 *collusion* 是合谋的名词形式。

*conspire* 也有相似的意思，密谋。con 也是一起的意思，spire 来自拉丁语
spirare 呼吸。一同呼吸、一个鼻孔出气，那自然是合伙的。不知道，为什么偷
偷的密谋。也许呼吸不易被察觉，所以有密谋的意思。

*References*
[[bibliography:~/docs/references.bib]]
