#+LAYOUT: post
#+TITLE: 单词本：compromise
#+TAGS: English
#+CATEGORIES: language

我一直搞不懂，信息安全中用到的这个词 *compromise* 应该怎么翻译。大概意思
是某个软件或者设备被坏人破解了，称为坏人继续干坏事的工具，比如添加了木
马病毒、勒索病毒或者蠕虫病毒。比如在 David Meier 等人的这篇论文
[[cite:&meier2022secprov]] 中写的：

The device cannot verify the authenticity of the operator
network. This may allow an adversary to (i) use stolen devices, (ii)
provide devices with *compromised* provisioning data, or (iii)
impersonate the operator and perform attacks with devices that are
already physically mounted in industrial plants (e.g., opening a
valve).

因为运营某设备的厂商无法验证设备是否完好，就会被坏人钻空子，一则，偷走
高价值设备，拿去用；二则在设备里装了损坏的文件，三则假冒是设备运营商，
进行一些恶意操作，比如打开化学反应罐的阀门，导致化工厂危化物泄露。

这里 *compromised* provisioning data 可以理解为篡改的设备上线数据。比如
把某个安全配置项的加密等级改低，这样在后续的攻击中，利用这个缺陷去进行
网络攻击。

compromise 有妥协的意思，也指东西受了污染人感染了病毒。从拟人的角度看，
设备中被恶意添加了病毒或篡改了文件，可以认为是感染了病毒。是不是可以翻
译为软件、系统或设备受了污染、或感染了病毒？

A device was *compromised*. 如果翻译成“一个设备已经被侵染了”，是不是比较
好理解？总比说“一个设备已经妥协了”更恰当吧。

*compromise* 也能做名词，比如 eventually they reached a *compromise*. 最终，
他们达成了妥协。

the secret of a happy marriage is *compromise*. 幸福婚姻的秘诀是相互妥协。

racism should be tackled without *compromise*. 种族主义问题不可妥协处理。

作为动词：in the end we *compromised* and deferred the dispute. 最后，我
们妥协了，延缓了争论。

don't *compromise* on safety. 安全问题不能妥协。

德语也有类似的 *der Kompromiss*

Kompromissentscheidung 妥协的决定。[[./2024-03-28-entscheidung][Entscheidung]] 是决定的意思。

法语 *la compromis*

aboutir à un *compromis* 达成妥协。

accepter un *compromis* 接受妥协。

*References*
[[bibliography:~/docs/references.bib]]
