:PROPERTIES:
:ID:       E0A84A31-E788-4CE3-BDA2-1569F630A4CE
:END:
#+LAYOUT: post
#+TITLE: 单词本：aplomb
#+TAGS: English
#+CATEGORIES: language

工业现场的设备最早是通过 4-20mA 这样的电流传输信号的。这样的信号传输限
制很大，一次只能传输一个值。于是，工程师们发明了 HART 这样的 FSK 叠加
信号，通过频率变换表达 0 和 1 。同时，又不影响 4-20mA 的电流。再后来，
基于 HART，有出现了 HART-IP 和 WirelessHART，这些协议利用 IP 或无线方
式进行通信，而核心的数据模型依然使用最早定义的 HART 数据模型。所以，这
段话说通过核心的 HART 数据模型泰然自若地处理数据细节。

WirelessHART already is being used to manage data streams from quite
sophisticated instruments such as vibration sensors for condition
monitoring. Entire frequency waveforms are being communicated via
HART-IP, and the core HART data model handles all that detail with
*aplomb*.

with aplomb 可以翻译为泰然自若。而 aplomb 则是沉着、泰然、自信的意思。
aplomb 其实来自法语的 à plomb， à 是朝向、向着，plomb 则来自拉丁语
plumbum 铅，所以化学元素里铅的名字就是 plumbum，缩写 Pb。那么，朝向铅
垂，就是垂直、沉着的意思咯。
- She passed the test *with aplomb*. 她泰然自若的通过了考试。（往往是在
  面对挑战的情况下展现出来的沉着状态）。
- Elle répondit avec *aplomb*. 她自信应对。法语里 aplomb 作为名词使用。
- Vous ne manquez pas *d'aplomb*! 你有些紧张，不够沉着。

英语里，铅 lead 也有领导的意思，那可能也是铅锤笔直朝向地面，所以就有领
导、引导的意思。大概铅有润滑作用，所以英语 lead 常形容顺畅、移动快：
- I had a *lead* foot in my younger days, and had quite a few
  accidents. 我年轻时候脚踩油门很快，不过很少出事故。

有时候，又形容很沉重：
- My legs feel like *lead*.

德语里，铅 das Blei，和 plumbum 差别有点大。因为铅的密度大，所以也常用
来比喻难受、沉重（schwer wie Blei，或直接 wie Blei）：
- Mir liegt es wie *Blei* in den Gliedern. 我疲倦得四肢动弹不得。
- Die Klöße liegen mir schwer wie *Blei* im Magen.
- Meine Glieder sind schwer wie *Blei*.

还有，刚巧，我在周末看《舒伯特和他的世界》 [[cite:&gibbs2014schubert]] 读
到了德语的铅笔，原来石墨黏土和木头做的铅笔，在德语里也叫铅笔呀： das
Bleistift

法语直接 plomb 传承自拉丁语 plumbum
- ciel de *plomb*, 形容浅灰色的天空，即 leaden  sky
- mer de *plomb*, 形容浅灰色的大海
- J'ai des jambes de *plomb*. 我腿像铅般重。

*References*
[[bibliography:~/docs/references.bib]]
