:PROPERTIES:
:ID:       E2092812-E43C-4772-A899-F7F610C31388
:END:
#+LAYOUT: post
#+TITLE: 单词本：zuversichtlich
#+TAGS: Deutsch
#+CATEGORIES: language

昨天刚写到我们公司鼓励包容和多样化的企业文化。今天就看到加拿大在这方面
做了个好的示范：

Premierminister Justin Trudeau gab am Mittwoch die Ernennung von
Generalleutnantin Jennie Carignan bekannt. "Ich bin *zuversichtlich*,
dass sie als Kanadas neue Chefin des Verteidigungsstabs dazu beitragen
wird, dass Kanada stärker und sicherer wird und bereit ist, sich den
globalen Sicherheitsherausforderungen zu stellen", sagte er.

加拿大任命 Jennie Carignan 为新一任 Chefin des Verteidigungsstabs，即
Chief of the Defence Staff 也就是国防参谋长。这个职位和国防部长相比应
该不相上下。一般来说国防部长负责对外事宜，而国防参谋长则负责内部指挥。
所以，国防参谋长具有更高的实权。

Jennie Carignan 之前的职务是 Generalleutnantin 即 Lieutenant General
中将。现在的职务则是上将。这位女将军 1990 年参军，履历很不错，还育有四
个小孩，其中两个也在加拿大军队工作。

这个任命可能还有其他目的。根据加拿大的统计，前一年军队里性犯罪案件频发：
Statistics Canada last December reported a "significant increase" in
rates of sexual misconduct in the Armed Forces over the preceding
year. 所以，安排 Jennie Carignan 担任参谋长或许还希望她来整顿军纪。

加拿大首相 Premierminister Justin Trudeau 发表言论称对其很有信心 Ich
bin *zuversichtlich*.

*zuversichtlich* 的意思是有信心的。 *sichtlich* 的意思是 visible 可见的。
因为可见所以自信，所以 *zuversichtlich* 就是有信心、很自信。

*sicht* 其实跟 *sight* 是一个意思。他们也就差了一个字母。一般来说 c 和 g
的发音是很相似的，一个轻一个浊罢了。

比如 Sie begrüßte uns mit *sichtlicher* Nervosität. 她跟我们打招呼的时候
明显地紧张。

如果我们对未来是明确可预见的，那就能从容不迫了。也就很有信心
*zuversichtlich* 。

例如，

Ich bin da wenig *zuversichtlich*. 我对此不太有信心。

Ich bin *zuversichtlich*, dass wir dieses Problem lösen werden. 我很有信
心我们能解决这些问题。

