#+LAYOUT: post
#+TITLE: 单词本：bout
#+TAGS: English
#+CATEGORIES: language

可怜的意大利女拳击手 Angela Carini 跟阿尔及利亚拳手 Imane Khelif 对打
了 46 秒就放弃比赛了……

An Italian boxer abandoned her *bout* at the Paris Olympics after only
46 seconds on Thursday, refusing to continue after taking a heavy
punch from an Algerian opponent who had been disqualified from last
year’s world championships over questions about her eligibility to
compete in women’s sports. [fn:1]

这个 Imane Khelif 去年好像是被禁赛了。原因是因为她基因里有男性特有的
XY 染色体。倒也不是她变性，是她天生就是这样的。极少数人生出来是女孩，
但是带有男性特有的 XY 染色体。这就会让她长得特别强壮。所以 Angela
Carini 被暴打一阵就投降了。

这里用到单词 bout 专指拳击比赛。

这个 bout 可能跟 bend 有关。bend 弯曲引申出一圈的意思。也就是一场比赛
了。要么是因为拳击赛场是被围起来的一圈。总之，bout 就是一场拳击比赛。

bout 的另一个意思是一次、一阵。比如 a bout of insomnia 一次失眠。a
bout of coughing 一阵咳嗽。

这里也可以用 fit 代替：a fit of coughing 一阵咳嗽。a fit of drinking
一场狂饮。a fit of illness 一场病。

* Footnotes

[fn:1] NYTimes. Italian Boxer Quits Bout, Sparking Furor Over Gender at
Olympics. https://www.nytimes.com/2024/08/01/world/olympics/boxer-quits-gender-angela-carini-imane-khelif.html
