#+LAYOUT: post
#+TITLE: 单词本：pièce de résistance
#+TAGS: English,Français
#+CATEGORIES: language

还是在看看 [[./2024-05-18-bane][Programming TypeScript]] [[cite:&cherny2019ts]] 的时候，读到这句：

You are now ready for TypeScript's *pièce de résistance* (or *raison
d'être*, if you're a functional programmer): functions.

这里，用到了两个法语外来词。括号里的 *raison d'être* ，之前我看《The Art
of Agile Product Ownership》 [[cite:&kelly2019po]] 的时候，遇到过，写了
[[./2024-03-23-raison-d-etre][《单词本：raison d'être》]]。

而 *pièce de résistance* 的意思则是 the best and most important or
exciting thing, often the last in a series of things。本来其实是法餐里
的主菜 chef-d'œuvre 的意思，引申为代表作品、最精彩的部分。

前面的这段话意思是说函数是 TypeScript 里最精彩的部分，是函数式程序员存
在的意义。

比如：
- The *pièce de résistance* was undoubtedly the creme brulee with
  strawberry compote.  奶油布雷+草莓果盘无疑是主菜。
- The *pièce de résistance* of the whole concert was when the two bands
  came onstage to perform together. 两支乐队合奏是整个音乐会最精彩部分。
- The waiter suggested we try the restaurant's *pièce de résistance*:
  the chocolate soufflé. 服务员建议餐馆的必点菜：巧克力舒芙蕾。
