#+LAYOUT: post
#+TITLE: 单词本：greenwashing
#+TAGS: English
#+CATEGORIES: language

昨天看到新闻说德国联邦消费者协会指出了拼多多海外平台 Temu 的一些诱导消
费者的问题：

Der Verbraucherzentrale Bundesverband (vzbv) hat den chinesischen
Online-Händler Temu abgemahnt. "Die Plattform Temu verunsichert und
übervorteilt Verbraucherinnen und Verbraucher mit willkürlich
erscheinenden Rabatten, fragwürdigen Bewertungen und manipulativen
Designs, das muss aufhören", sagte vzbv-Chefin Ramona Pop den
Zeitungen der Funke Mediengruppe vom Dienstag. Das Unternehmen
verstoße gegen EU-Verbraucherschutzgesetze und betreibe darüber hinaus
*Greenwashing*.

主要说的是一些看起来是在操作消费者的折扣策略，有问题的评分机制，还有诱
导性的设计等。最后他们认为 Temu 违反了欧盟消费者保护法，还涉嫌
Greenwashing。

我查了下，Greenwashing 是从英语里过来的，意思是企业夸大自身环保行为，
从而误导消费者。中文有翻译为“漂绿”。

这个词出现的背景是现在全球都在提倡可持续性发展，很多负责任的企业会在生
产经营过程中追求绿色环保。而有些企业则热衷于宣传自己的绿色环保属性，期
望得到消费者的好感，提出各种绿色环保概念。儒家提倡中庸，很多过度宣传的
行为，往往隐藏着不好的目的。greenwashing 漂绿就是描述这种企业过度宣传
自身绿色环保属性诱导消费者的行为。

greenwashing 是从更早的 whitewash 演变而来。Whitewash 指的大概是在
1960 年代，酒店为了节约毛巾而宣称环保的行为：

The term originated in the 1960s, when the hotel industry devised one
of the most blatant examples of greenwashing. They placed notices in
hotel rooms asking guests to reuse their towels to save the
environment. The hotels enjoyed the benefit of lower laundry costs.

